### ISSUE TITLE
The setbucketlifecycle method threw an exception "'date'must be at midnight GMT"

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1103]
Code:
```
import io.minio.GetBucketLifecycleArgs;
import io.minio.MakeBucketArgs;
import io.minio.MinioClient;
import io.minio.RemoveBucketArgs;
import io.minio.SetBucketLifecycleArgs;
import io.minio.messages.Expiration;
import io.minio.messages.LifecycleConfiguration;
import io.minio.messages.LifecycleRule;
import io.minio.messages.RuleFilter;
import io.minio.messages.Status;
import java.time.ZonedDateTime;
import java.util.LinkedList;
import java.util.List;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioClient client =
        MinioClient.builder()
            .endpoint("http://localhost:9000")
            .credentials("minio", "minio123")
            .build();
    client.traceOn(System.out);
    String bucketName = "issue-1097";
    client.makeBucket(MakeBucketArgs.builder().bucket(bucketName).build());

    List<LifecycleRule> rules = new LinkedList<>();
    rules.add(
        new LifecycleRule(
            Status.ENABLED,
            null,
            new Expiration(ZonedDateTime.now(), null, null),
            new RuleFilter("logs/"),
            "rule2",
            null,
            null,
            null));
    LifecycleConfiguration config = new LifecycleConfiguration(rules);
    client.setBucketLifecycle(
        SetBucketLifecycleArgs.builder().bucket(bucketName).config(config).build());

    config = client.getBucketLifecycle(GetBucketLifecycleArgs.builder().bucket(bucketName).build());
    System.out.println("Rule Filter Prefix: " + config.rules().get(0).filter().prefix());

    client.removeBucket(RemoveBucketArgs.builder().bucket(bucketName).build());
  }
}
```
Output:
```
---------START-HTTP---------
PUT /test?lifecycle= HTTP/1.1
Host: 127.0.0.1:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows Server 2019; amd64) minio-java/8.0.0
Content-MD5: gfmBhDaIhJGQV9LTclG69w==
x-amz-content-sha256: c703f477f19b66696b06b6e21ffcfc40ad6301f00baa475867f9857faee3ab9f
x-amz-date: 20201108T013104Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201108/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Date>2020-11-08T01:31:04.072Z</Date></Expiration><Filter><Prefix>logs/</Prefix></Filter><ID>rule2</ID><Status>Enabled</Status></Rule></LifecycleConfiguration>
HTTP/1.1 400
Accept-Ranges: bytes
Content-Length: 285
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-10-28T08-16-50Z
Vary: Origin
X-Amz-Request-Id: 1645643F0A83DC00
X-Xss-Protection: 1; mode=block
Date: Sun, 08 Nov 2020 01:31:04 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>&#39;Date&#39; must be at midnight GMT</Message><BucketName>test</BucketName><Resource>/test</Resource><RequestId>1645643F0A83DC00</RequestId><HostId>38cb55db-84d3-44b7-a0a5-526fa797829c</HostId></Error>
----------END-HTTP----------
```
Exception:
```
io.minio.errors.ErrorResponseException: 'Date' must be at midnight GMT
	at io.minio.MinioClient.execute(MinioClient.java:767) ~[minio-8.0.0.jar:8.0.0]
	at io.minio.MinioClient.execute(MinioClient.java:563) ~[minio-8.0.0.jar:8.0.0]
	at io.minio.MinioClient.executePut(MinioClient.java:896) ~[minio-8.0.0.jar:8.0.0]
	at io.minio.MinioClient.setBucketLifecycle(MinioClient.java:3058) ~[minio-8.0.0.jar:8.0.0]

```

**Comment by balamurugana** [comment]
As the error message suggested, adjust your date in expiration accordingly.

**Comment by 4714407** [comment]
Can you give me an example of not reporting mistakes, thank you

**Comment by balamurugana** [comment]
Please go through https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html how to use `ZonedDateTime`

**Comment by 4714407** [comment]
I set the correct ZonedDateTime, but I still report an error. Can you provide a no error setting?

**Comment by 4714407** [comment]
The exception is because the hours, minutes and seconds are set

**Comment by 4714407** [comment]
Why not support hours, minutes and seconds, which means that you can't set a local date?

**Comment by harshavardhana** [comment]
> Why not support hours, minutes and seconds, which means that you can't set a local date?

AWS S3 spec mandates UTC @4714407

**Comment by 4714407** [comment]
Thank you. I see. It's the damn S3 again.
