### ISSUE TITLE
When set MinIO `export MINIO_CACHE_COMMIT=writeback`, uploading files using minio-java SDK throws NullPointerException

### ISSUE THREAD

**Issue by blinkfox** [minio/minio-java#1127]
When I use MinIO Gateway for NAS, I set

```bash
export MINIO_CACHE_COMMIT=writeback
```

Then using minio-java SDK to upload files, it will throw a `NullPointerException`:

```bash
java.lang.NullPointerException: null
	at io.minio.MinioClient.putObject(MinioClient.java:7596) ~[minio-7.1.4.jar:7.1.4]
	at io.minio.MinioClient.putObject(MinioClient.java:4682) ~[minio-7.1.4.jar:7.1.4]
	at io.minio.MinioClient.putObject(MinioClient.java:4881) ~[minio-7.1.4.jar:7.1.4]
	at com.blinkfox.optimus.tcs.minio.service.MinioClientService.putObject(MinioClientService.java:155) ~[classes/:na]
	at com.blinkfox.optimus.tcs.minio.service.MinioService.upload(MinioService.java:80) ~[classes/:na]
	at com.blinkfox.optimus.tcs.minio.controller.MinioController.upload(MinioController.java:67) ~[classes/:na]
```

I debugged and found that the cause of the exception was the value of `response.header("ETag")` is `null`:

```java
try (Response response =
    execute(
        Method.PUT,
        bucketName,
        objectName,
        getRegion(bucketName, region),
        headers,
        extraQueryParams,
        data,
        length)) {
    return new ObjectWriteResponse(
        response.headers(),
        bucketName,
        region,
        objectName,
        response.header("ETag").replaceAll("\"", ""),
        response.header("x-amz-version-id"));
}
```

The version of minio I used is `RELEASE.2020-11-19T23-48-16Z`, the version of minio-java SDK is `7.1.4`, I tried the `8.0.1` version and still have this problem.

**Comment by balamurugana** [comment]
`ETag` must be returned from the server on successful upload.
