### ISSUE TITLE
Skip object locking tests on NAS gateway

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#1129]
```
~ minio gateway nas ~/test
Endpoint:  http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                  
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mynas http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

```
~  ./gradlew runFunctionalTest -Pendpoint=http://localhost:9000 -PaccessKey=minio -PsecretKey=minio123
...
listenBucketNotification()
listObjects()
putObject()
<FAILED> putObject() [with retention]
error occurred
ErrorResponse(code = NoSuchBucket, message = The specified bucket does not exist, bucketName = minio-java-test-141qq7u, objectName = null, resource = /minio-java-test-141qq7u, requestId = 164BE11C0355127F, hostId = 6504773c-3b8b-4ecc-af50-bf3d360ba49f)
request={method=GET, url=http://localhost:9000/minio-java-test-141qq7u?location=, headers=Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.0.2-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20201129T044642Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201129/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=404, headers=Accept-Ranges: bytes
Content-Length: 318
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 164BE11C0355127F
X-Xss-Protection: 1; mode=block
Date: Sun, 29 Nov 2020 04:46:42 GMT
}

        at io.minio.MinioClient.execute(MinioClient.java:775)
        at io.minio.MinioClient.getRegion(MinioClient.java:807)
        at io.minio.MinioClient.putObject(MinioClient.java:4534)
        at io.minio.MinioClient.putObject(MinioClient.java:2696)
        at io.minio.MinioClient.putObject(MinioClient.java:2813)
        at FunctionalTest.testPutObject(FunctionalTest.java:756)
        at FunctionalTest.putObject(FunctionalTest.java:929)
        at FunctionalTest.runObjectTests(FunctionalTest.java:3725)
        at FunctionalTest.runTests(FunctionalTest.java:3757)
        at FunctionalTest.main(FunctionalTest.java:3901)

> Task :functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional:runFunctionalTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 35s
4 actionable tasks: 1 executed, 3 up-to-date
```

This is from release branch 8.0.2 @balamurugana

**Comment by harshavardhana** [comment]
Looks like this happens with master as well

**Comment by balamurugana** [comment]
commit id bdd094bc39275a0543484c09f4fb99ce3fe14787 of minio server returns below
```
[bala@localhost minio]$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio gateway nas ~/test
Endpoint:  http://192.168.43.140:9000  http://172.17.0.1:9000  http://127.0.0.1:9000    
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.43.140:9000  http://172.17.0.1:9000  http://127.0.0.1:9000    

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mynas http://192.168.43.140:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

```java

import io.minio.MakeBucketArgs;
import io.minio.MinioClient;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioClient minioClient =
        MinioClient.builder()
            .endpoint("http://localhost:9000")
            .credentials("minio", "minio123")
            .build();

    minioClient.makeBucket(
        MakeBucketArgs.builder().bucket("my-bucketname-with-object-lock").objectLock(true).build());
    System.out.println("my-bucketname-with-object-lock is created successfully");
  }
}
```

```sh
[bala@localhost minio-java]$ javac -cp api/build/libs/minio-8.0.3-DEV-all.jar Check.java && java -cp api/build/libs/minio-8.0.3-DEV-all.jar:. Check
Exception in thread "main" error occurred
ErrorResponse(code = NotImplemented, message = A header you provided implies functionality that is not implemented, bucketName = my-bucketname-with-object-lock, objectName = null, resource = /my-bucketname-with-object-lock, requestId = 164BEAB1B9269E9A, hostId = 36e6bd6b-3401-492c-a3bf-c6e32de45b68)
request={method=PUT, url=http://localhost:9000/my-bucketname-with-object-lock, headers=x-amz-bucket-object-lock-enabled: true
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.0.3-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20201129T074221Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201129/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-bucket-object-lock-enabled;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Length: 366
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 164BEAB1B9269E9A
X-Xss-Protection: 1; mode=block
Date: Sun, 29 Nov 2020 07:42:21 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:775)
	at io.minio.MinioClient.makeBucket(MinioClient.java:2266)
	at Check.main(Check.java:12)
```

The test supposes to fail at https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L689

Please reopen the issue with appropriate requirements.

**Comment by harshavardhana** [comment]
@balamurugana the failure is at putObject() - please don't close the issue the issue 

- is that makeBucket() with locking enable never gets created
- so the putObject() with retention settings fails

**Comment by harshavardhana** [comment]
All the retention locking-related tests should be turned off if the makeBucket with object locking doesn't get created. Functional tests currently lack this support.

**Comment by harshavardhana** [comment]
> The test supposes to fail at https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L689

That test simply ignores NotImplemented and moves on @balamurugana
