### ISSUE TITLE
NoSuchMethodError - addUnsafeNonAscii

### ISSUE THREAD

**Issue by marvinosswald** [minio/minio-java#1148]
it appears like if i don't set the Content-Encoding explicitly this is bound to fail.

```java
java.lang.NoSuchMethodError: okhttp3.Headers$Builder.addUnsafeNonAscii(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/Headers$Builder;
```

https://github.com/minio/minio-java/blob/ff9c42747ead0949875740a0c5f8e029a47d704c/api/src/main/java/io/minio/MinioClient.java#L436-L440

Info:

Java: 8
Minio Java SDK: 8.0.3
okhttp3: 3.8.1

**Comment by balamurugana** [comment]
You would need to use okhttp v4.8.1 and okhttp 3.x is no longer supported.

**Comment by marvinosswald** [comment]
i couldn't get it to use 4.8.1 but by excluding it and directly depending on it:

```xml
<dependency>
	<groupId>io.minio</groupId>
	<artifactId>minio</artifactId>
	<version>8.0.3</version>
	<exclusions>
		<exclusion>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.9.0</version>
		</dependency>
```

but now it got a new `NoSuchMethodError`:

```java
java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B

	at okio.Segment.writeTo(Segment.kt:169)
	at okio.Segment.compact(Segment.kt:152)
	at okio.Buffer.write(Buffer.kt:1842)
	at okio.Buffer.read(Buffer.kt:1854)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174)
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
	at okio.Options$Companion.of(Options.kt:72)
	at okhttp3.internal.Util.<clinit>(Util.kt:71)
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
	at okhttp3.HttpUrl.parse(HttpUrl.kt)
	at io.minio.MinioClient$Builder.getBaseUrl(MinioClient.java:5003)
	at io.minio.MinioClient$Builder.endpoint(MinioClient.java:5015)

```

is minio-java supposed to work with java 8 or did i miss something ?

**Comment by balamurugana** [comment]
Java 8/11 are supported in `minio-java`. You would need to resolve dependencies correctly. Please refer https://github.com/minio/minio-java/blob/master/build.gradle#L53-L69
