### ISSUE TITLE
failed to getPresignedPostFormData

### ISSUE THREAD

**Issue by usageek1266** [minio/minio-java#1153]
failed to getPresignedPostFormData
```
Connected to the target VM, address: '127.0.0.1:0', transport: 'socket'
Exception in thread "main" java.lang.IllegalArgumentException: key condition must be set
	at io.minio.PostPolicy.formData(PostPolicy.java:193)
	at io.minio.MinioClient.getPresignedPostFormData(MinioClient.java:1635)
	at test1.main(test1.java:42)
```

```
import io.minio.MinioClient;
import io.minio.PostPolicy;
import io.minio.errors.MinioException;
import java.io.File;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.time.ZonedDateTime;
import java.util.Map;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class test1 {
    /** MinioClient.presignedPostPolicy() example. */
    public static void main(String[] args)
            throws IOException, NoSuchAlgorithmException, InvalidKeyException {
        try {
            /* play.min.io for test and development. */
            MinioClient minioClient =
                    MinioClient.builder()
                            .endpoint("http://127.0.0.1:8000/")
                            .credentials("yly", "yly")
                            .build();

            String bucket_name = "test2";
            String object_name = "hello.txt";
            // Create new post policy for 'my-bucketname' with 7 days expiry from now.
            PostPolicy policy = new PostPolicy(bucket_name, ZonedDateTime.now().plusDays(7));

            // Add condition that 'key' (object name) equals to 'my-objectname'.
            policy.addStartsWithCondition("key", "");

            // Add condition that 'Content-Type' starts with 'image/'.
            policy.addStartsWithCondition("Content-Type", "");

            // Add condition that 'content-length-range' is between 0kiB to 10MiB.
            policy.addContentLengthRangeCondition(0, 10 * 1024 * 1024);

            Map<String, String> formData = minioClient.getPresignedPostFormData(policy);

            // Upload an image using POST object with form-data.
            MultipartBody.Builder multipartBuilder = new MultipartBody.Builder();
            multipartBuilder.setType(MultipartBody.FORM);
            for (Map.Entry<String, String> entry : formData.entrySet()) {
                multipartBuilder.addFormDataPart(entry.getKey(), entry.getValue());
            }

            multipartBuilder.addFormDataPart("key", object_name);
            multipartBuilder.addFormDataPart("Content-Type", "image/png");
            multipartBuilder.addFormDataPart("file", object_name, RequestBody.create(new File("D:/nohup.out"), null));

            for (Map.Entry<String, String> entry : formData.entrySet()) {
                System.out.println(entry.getKey() + "=" + entry.getValue());
            }
        } catch (MinioException e) {
            System.out.println("Error occurred: " + e);
        }
    }
}
```

https://github.com/minio/minio-java/blob/8ace1e91a78bd77128acaf5d7fd970405c6efe9e/api/src/main/java/io/minio/PostPolicy.java#L192

i think the correct is
```
    if (!conditions.get(EQ).containsKey("key") && !conditions.get(STARTS_WITH).containsKey("key")) {
      throw new IllegalArgumentException("key condition must be set");
    }
```

**Comment by joke-lee** [comment]
https://github.com/minio/minio-java/pull/1154 fix this
