### ISSUE TITLE
minioClient.putObject() get NullPointerException

### ISSUE THREAD

**Issue by shuangovo** [minio/minio-java#1172]
````java
minioClient.putObject(
    PutObjectArgs.builder()
        .bucket(bucket)
        .contentType(file.getContentType())
        .object(object)
        .userMetadata(userMeta)
        .stream(file.getInputStream(), file.getSize(), -1)
        .build()
);

java.lang.NullPointerException
	at okhttp3.Headers$Builder.addLenient(Headers.java:394)
	at okhttp3.Headers$Builder.addUnsafeNonAscii(Headers.java:334)
	at io.minio.MinioClient.httpHeaders(MinioClient.java:460)
	at io.minio.MinioClient.putObject(MinioClient.java:4535)
	at io.minio.MinioClient.putObject(MinioClient.java:2696)
	at io.minio.MinioClient.putObject(MinioClient.java:2813)
	at com.ovo.minio.controller.UploadController.uploadImage(UploadController.java:53)
````
I have checked minioClient and args are not null,but get a NullPointerException

**Comment by balamurugana** [comment]
Make sure you use latest version of minio-java and okhttp v4.8.1

**Comment by shuangovo** [comment]
@balamurugana 
my minio-java version is 8.0.3
I just now changed the okhttp version to 4.8.1,got a new exception
````java
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.Headers$Builder.addUnsafeNonAscii, parameter value
	at okhttp3.Headers$Builder.addUnsafeNonAscii(Headers.kt)
	at io.minio.MinioClient.httpHeaders(MinioClient.java:460)
	at io.minio.MinioClient.putObject(MinioClient.java:4552)
	at io.minio.MinioClient.putObject(MinioClient.java:2713)
	at io.minio.MinioClient.putObject(MinioClient.java:2830)
	at com.ovo.minio.controller.UploadController.uploadImage(UploadController.java:59)
````
how can I resolve this

**Comment by balamurugana** [comment]
Make sure your user metadata must not contain `null` key/value

**Comment by shuangovo** [comment]
it works for me,thanks
