### ISSUE TITLE
Builder crashing when defining bucket name

### ISSUE THREAD

**Issue by Tadejo9** [minio/minio-java#1187]
Hello,

I am trying to download a zip file from our server using java client api in android app.

### Adding the dependancy
dependencies {
    compile 'io.minio:minio:8.2.1' //replaced for bottom line
    implementation 'io.minio:minio:8.2.1'
}

### Creating MinioManager class

```
public class MinioManager {

    private final MinioClient minioClient;

    public MinioManager() {
        minioClient = MinioClient.builder()
                .endpoint("url")
                .credentials("uname", "pass")
                .build();
    }

    public void download() {
        try {
            minioClient.downloadObject(
                    DownloadObjectArgs.builder()
                    .bucket("bucket-name") //code fails here
                    .object("filename.zip")
                    .filename("file-path")
                    .build()
            );
        } catch (ErrorResponseException | InsufficientDataException | InternalException | InvalidKeyException | InvalidResponseException | IOException | NoSuchAlgorithmException | ServerException | XmlParserException e) {
            e.printStackTrace();
        }
    }
}
```

### Calling download method in activity

```
MinioManager minioManager = new MinioManager();
minioManager.download();
```

I've narrowed down to the line where app fails and it is BucketArgs.java line 73 with error:

`java.lang.BootstrapMethodError: Exception from call site #260 bootstrap method`

I have debugged the code and when code enters BucketArgs bucket method
```
    @SuppressWarnings("unchecked") // Its safe to type cast to B as B extends this class.
    public B bucket(String name) {
      validateBucketName(name);
      operations.add(args -> args.bucketName = name);
      return (B) this;
    }
```

the following property does not exist.

`args.bucketName = Cannot find local variable 'args'`

**Comment by balamurugana** [comment]
You have to check java environment and minio-java dependencies properly. If you still face the problem, reopen the issue with appropriate stacktrace.

**Comment by Tadejo9** [comment]
Environment and minio-java dependencies are ok.

Below stacktrace is provided.
```

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <id>, PID: 11095
    java.lang.BootstrapMethodError: Exception from call site #260 bootstrap method
        at io.minio.BucketArgs$Builder.bucket(BucketArgs.java:73)
        at org.kaldi.demo.MinioManager.download(MinioManager.java:38)
        at org.kaldi.demo.KaldiActivity.downloadModel(KaldiActivity.java:133)
        at org.kaldi.demo.KaldiActivity.onCreate(KaldiActivity.java:150)
        at android.app.Activity.performCreate(Activity.java:7340)
        at android.app.Activity.performCreate(Activity.java:7331)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3106)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3269)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at io.minio.BucketArgs$Builder.bucket(BucketArgs.java:73) 
        at org.kaldi.demo.MinioManager.download(MinioManager.java:38) 
        at org.kaldi.demo.KaldiActivity.downloadModel(KaldiActivity.java:133) 
        at org.kaldi.demo.KaldiActivity.onCreate(KaldiActivity.java:150) 
        at android.app.Activity.performCreate(Activity.java:7340) 
        at android.app.Activity.performCreate(Activity.java:7331) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3106) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3269) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7094) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by Tadejo9** [comment]
Thank you...This resolved the issue.

After that i Initialized  MinioManager in seperate thread and called download method. Like this:

```
    private static class DownloadModelsTask extends AsyncTask<Void, Void, Exception> {
        WeakReference<KaldiActivity> activityReference;

        DownloadModelsTask(KaldiActivity activity) {
            this.activityReference = new WeakReference<>(activity);
        }

        @Override
        protected Exception doInBackground(Void... params) {
            try {
                MinioManager minioManager = new MinioManager();
                minioManager.download();
            } catch (Exception e) {
                return e;
            }
            return null;
        }

        @Override
        protected void onPostExecute(Exception result) {
            System.out.println("YAAAAY downloaded!");
        }
    }
```

App launched and even the permission modal for microphone popped up. But then this stack appeared

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: <id>, PID: 18927
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
        at org.simpleframework.xml.stream.StreamProvider.<init>(StreamProvider.java:61)
        at org.simpleframework.xml.stream.ProviderFactory.getInstance(ProviderFactory.java:38)
        at org.simpleframework.xml.stream.NodeBuilder.<clinit>(NodeBuilder.java:45)
        at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71)
        at org.simpleframework.xml.core.Persister.read(Persister.java:562)
        at org.simpleframework.xml.core.Persister.read(Persister.java:462)
        at io.minio.Xml.unmarshal(Xml.java:53)
        at io.minio.S3Base.getRegion(S3Base.java:695)
        at io.minio.S3Base.execute(S3Base.java:464)
        at io.minio.S3Base.executeHead(S3Base.java:725)
        at io.minio.S3Base.statObject(S3Base.java:1497)
        at io.minio.MinioClient.statObject(MinioClient.java:217)
        at io.minio.MinioClient.downloadObject(MinioClient.java:301)
        at org.kaldi.demo.MinioManager.download(MinioManager.java:43)
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:237)
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:226)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLInputFactory" on path: DexPathList[[zip file "/data/app/org.vosk.demo-gvwx92yl84-gZp1E9r3dkA==/base.apk"],nativeLibraryDirectories=[/data/app/org.vosk.demo-gvwx92yl84-gZp1E9r3dkA==/lib/arm, /data/app/org.vosk.demo-gvwx92yl84-gZp1E9r3dkA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.simpleframework.xml.stream.StreamProvider.<init>(StreamProvider.java:61) 
        at org.simpleframework.xml.stream.ProviderFactory.getInstance(ProviderFactory.java:38) 
        at org.simpleframework.xml.stream.NodeBuilder.<clinit>(NodeBuilder.java:45) 
        at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71) 
        at org.simpleframework.xml.core.Persister.read(Persister.java:562) 
        at org.simpleframework.xml.core.Persister.read(Persister.java:462) 
        at io.minio.Xml.unmarshal(Xml.java:53) 
        at io.minio.S3Base.getRegion(S3Base.java:695) 
        at io.minio.S3Base.execute(S3Base.java:464) 
        at io.minio.S3Base.executeHead(S3Base.java:725) 
        at io.minio.S3Base.statObject(S3Base.java:1497) 
        at io.minio.MinioClient.statObject(MinioClient.java:217) 
        at io.minio.MinioClient.downloadObject(MinioClient.java:301) 
        at org.kaldi.demo.MinioManager.download(MinioManager.java:43) 
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:237) 
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:226) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I debugged the app. `builder` returned the builder object, but when adding bucket:

```
args.bucketName = Cannot find local variable 'args'
```

But this time it went to return statement of `bucket` method.

`object` method executed ok with same `Cannot find local variable 'args'`.

`filename` same as `object`

Then there is a "pause" in execution. I believe it is a download request. And then i recieve stack mentioned above.
