### ISSUE TITLE
Request URL builds incorrectly

### ISSUE THREAD

**Issue by Tadejo9** [minio/minio-java#1188]
## Environment information
Android studio: 4.1.3
Runtime version: 1.8.0_242

Macbook Pro M1
Big Sur 11.2.3

minio:8.2.1

Running on Galaxy J4+, Android 9

## Issue
I am trying to fetch a zip file from our server. When the request finishes app crashes with the following stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: <id>, PID: 20378
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
        at org.simpleframework.xml.stream.StreamProvider.<init>(StreamProvider.java:61)
        at org.simpleframework.xml.stream.ProviderFactory.getInstance(ProviderFactory.java:38)
        at org.simpleframework.xml.stream.NodeBuilder.<clinit>(NodeBuilder.java:45)
        at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71)
        at org.simpleframework.xml.core.Persister.read(Persister.java:562)
        at org.simpleframework.xml.core.Persister.read(Persister.java:462)
        at io.minio.Xml.unmarshal(Xml.java:53)
        at io.minio.S3Base.getRegion(S3Base.java:695)
        at io.minio.S3Base.execute(S3Base.java:464)
        at io.minio.S3Base.executeHead(S3Base.java:725)
        at io.minio.MinioClient.bucketExists(MinioClient.java:1135)
        at org.kaldi.demo.MinioManager.exists(MinioManager.java:86)
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:240)
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:229)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLInputFactory" on path: DexPathList[[zip file "/data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/base.apk"],nativeLibraryDirectories=[/data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/lib/arm, /data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.simpleframework.xml.stream.StreamProvider.<init>(StreamProvider.java:61) 
        at org.simpleframework.xml.stream.ProviderFactory.getInstance(ProviderFactory.java:38) 
        at org.simpleframework.xml.stream.NodeBuilder.<clinit>(NodeBuilder.java:45) 
        at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71) 
        at org.simpleframework.xml.core.Persister.read(Persister.java:562) 
        at org.simpleframework.xml.core.Persister.read(Persister.java:462) 
        at io.minio.Xml.unmarshal(Xml.java:53) 
        at io.minio.S3Base.getRegion(S3Base.java:695) 
        at io.minio.S3Base.execute(S3Base.java:464) 
        at io.minio.S3Base.executeHead(S3Base.java:725) 
        at io.minio.MinioClient.bucketExists(MinioClient.java:1135) 
        at org.kaldi.demo.MinioManager.exists(MinioManager.java:86) 
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:240) 
        at org.kaldi.demo.KaldiActivity$DownloadModelsTask.doInBackground(KaldiActivity.java:229) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I also inspected the url which is built on request and it is wrong.

`https://play.min.io/0ohlbsftyif7u78lphc6c6ck6av0vjnk?location=`

There is no minio in the beggining of the path.

**Comment by balamurugana** [comment]
Resolve this `Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLInputFactory" on path: DexPathList[[zip file "/data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/base.apk"],nativeLibraryDirectories=[/data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/lib/arm, /data/app/org.vosk.demo-G8yoQRT7978G0wYJiPMEbA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

**Comment by Tadejo9** [comment]
I have managed to resolve it by following this [issue](https://github.com/FasterXML/jackson-dataformat-xml/issues/142).

Bucket is created so it is resolved. Thank you.
