### ISSUE TITLE
MinioClient.builder() throw exception because of jar confliction

### ISSUE THREAD

**Issue by wwulfric** [minio/minio-java#1234]
Run `MinioClient.builder();` simply and get an exception:

```
java.lang.NoSuchFieldError: Companion

	at okhttp3.internal.Util.<clinit>(Util.kt:72)
	at okhttp3.RequestBody$Companion.create(RequestBody.kt:145)
	at okhttp3.RequestBody$Companion.create$default(RequestBody.kt:143)
	at okhttp3.RequestBody.create(RequestBody.kt)
	at io.minio.S3Base.<clinit>(S3Base.java:105)
```

It seems because of jar confliction. But I don't know why.

**Comment by balamurugana** [comment]
You would need to have `okhttp v4.8.1` and its required dependencies correctly.

**Comment by wwulfric** [comment]
![image](https://user-images.githubusercontent.com/8315997/133612113-d4e3fc67-07e3-47fa-a576-7f1cb13a349a.png)
@balamurugana Yes I've checked okhttp version.

**Comment by balamurugana** [comment]
Below is the dependency tree
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.carrotsearch.thirdparty:simple-xml-safe:2.7.1
+--- com.google.guava:guava:30.0-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:3.5.0
|    +--- com.google.errorprone:error_prone_annotations:2.3.4
|    \--- com.google.j2objc:j2objc-annotations:1.3
+--- com.squareup.okhttp3:okhttp:4.8.1
|    +--- com.squareup.okio:okio:2.7.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.70 -> 1.3.72
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
|    |    |    \--- org.jetbrains:annotations:13.0
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.70 -> 1.3.72
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
+--- com.fasterxml.jackson.core:jackson-annotations:2.11.2 -> 2.9.6
+--- com.fasterxml.jackson.core:jackson-core:2.11.2
\--- com.fasterxml.jackson.core:jackson-databind:2.11.2
     +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2 -> 2.9.6
     \--- com.fasterxml.jackson.core:jackson-core:2.11.2
```
