### ISSUE TITLE
statObject and getObject throw Exception when used with notMatchETag()

### ISSUE THREAD

**Issue by jeromewaibel** [minio/minio-java#1296]
minio SDK version: 8.3.6
server is latest docker image: minio/minio:RELEASE.2022-02-07T08-17-33Z

If I call 

```
        val statObjectArgs = StatObjectArgs.builder()
            .notMatchETag("etag of img.png")
            .bucket("bucket")
            .`object`("img.png")
            .build()
        val statObjectResponse = minioClient.statObject(statObjectArgs)
```` 

I get this error

```
io.minio.errors.InternalException: unhandled HTTP code 304.  Please report this issue at https://github.com/minio/minio-java/issues
	at io.minio.S3Base.execute(S3Base.java:626) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.S3Base.execute(S3Base.java:440) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.S3Base.executeHead(S3Base.java:703) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.S3Base.statObject(S3Base.java:1381) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.MinioClient.statObject(MinioClient.java:208) ~[minio-8.3.6.jar:8.3.6]
```

If I call

```
        val getObjectArgs = GetObjectArgs.Builder()
            .notMatchETag("etag of img.png")
            .bucket("bucket")
            .`object`("img.png")
            .build()
        val getObjectResponse = minioClient.getObject(getObjectArgs)
```

I get this error

```
io.minio.errors.InvalidResponseException: Non-XML response from server. Response code: 304, Content-Type: null, body: 
	at io.minio.S3Base.execute(S3Base.java:555) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.S3Base.execute(S3Base.java:440) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.S3Base.executeGet(S3Base.java:693) ~[minio-8.3.6.jar:8.3.6]
	at io.minio.MinioClient.getObject(MinioClient.java:248) ~[minio-8.3.6.jar:8.3.6]
```

Maybe I misunderstood the API?

I'm in an HTTP controller and have an ETag from the HTTP request. I would like to check in the bucket whether the file for this ETag ist still valid so I can either return a 304 code or read and deliver the content and return 200.

**Comment by balamurugana** [comment]
I guess the response is not from MinIO server. May be your proxy server or some other server is responding for the request. Can you confirm by doing `statObject()` without any filter matching like
```java
        val statObjectArgs = StatObjectArgs.builder()
            .bucket("bucket")
            .`object`("img.png")
            .build()
        val statObjectResponse = minioClient.statObject(statObjectArgs)
```
If above code works, please enable `minioClient.traceOn()` and provide the output.

**Comment by jeromewaibel** [comment]
I pretty sure there is no proxy involved, as I'm running the queries against a local docker container (minio is on localhost:9000).

Here is the trace of the stat call **without notMatchETag** (working fine)

```
---------START-HTTP---------
GET /bucket?location= HTTP/1.1
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.3.6
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220208T120812Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 128
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16D1CE3AF14D9AE4
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 08 Feb 2022 12:08:11 GMT

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
HEAD /bucket/img.png HTTP/1.1
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.3.6
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220208T120812Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 26780
Content-Security-Policy: block-all-mixed-content
Content-Type: image/png
ETag: "6f590a7f532b4577cc54c3d904ece89a"
Last-Modified: Tue, 08 Feb 2022 12:01:20 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16D1CE3AF4D82C24
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 08 Feb 2022 12:08:11 GMT


----------END-HTTP----------
```

and here is the trace **with notMatchETag**

```
---------START-HTTP---------
GET /bucket?location= HTTP/1.1
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.3.6
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220208T120931Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 128
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16D1CE4D5AAA86C0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 08 Feb 2022 12:09:30 GMT

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
HEAD /bucket/img.png HTTP/1.1
if-none-match: "6f590a7f532b4577cc54c3d904ece89a"
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.3.6
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220208T120931Z
Authorization: ██

HTTP/1.1 304
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
ETag: "6f590a7f532b4577cc54c3d904ece89a"
Last-Modified: Tue, 08 Feb 2022 12:01:20 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16D1CE4D5E4F6BD8
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 08 Feb 2022 12:09:30 GMT

----------END-HTTP----------
```

I peeked into S3Base.execute(S3Base.java:626) from the stacktrace, The switch statement there simply does not handle 304 at all.

**Comment by balamurugana** [comment]
As per S3 specification, HTTP status code 304 is for `if-none-match` condition is false. I sent a PR https://github.com/minio/minio-java/pull/1297 to return `ServerException` for such cases.
