### ISSUE TITLE
Failed to get object in private S3 Compatible Service.

### ISSUE THREAD

**Issue by Paradox98** [minio/minio-java#1326]
```ErrorResponse(code = AccessDenied, message = null, bucketName = bucket, objectName = null, resource = null, requestId = tx000000000000000473601-006274a9f1-1f4c0c-default, hostId = 1f4c0c-default-default)
request={method=GET, url=http://IP/bucket?location=, headers=Host: 172.34.57.31
Accept-Encoding: identity
User-Agent: MinIO (Windows Server 2016; amd64) minio-java/8.3.7
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220506T045414Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220506/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=403, headers=Server: openresty/1.19.9.1
Date: Fri, 06 May 2022 04:54:09 GMT
Content-Type: application/xml
Content-Length: 233
Connection: keep-alive
x-amz-request-id: tx000000000000000473601-006274a9f1-1f4c0c-default
Accept-Ranges: bytes
}
        at io.minio.S3Base.execute(S3Base.java:636)
        at io.minio.S3Base.getRegion(S3Base.java:660)
        at io.minio.S3Base.execute(S3Base.java:444)
        at io.minio.S3Base.executeGet(S3Base.java:684)
        at io.minio.MinioClient.getObject(MinioClient.java:248)
}
```
I am using minio java sdk to obtain private cloud object storage. I know the region is "", but minioclient will request, and my account does not have permission to obtain region information, at this time I think minio should catch the exception and continue to use "" as the region value.

minio java sdk version 8.3.7

**Comment by balamurugana** [comment]
It is not possible to support empty string as region which will break with AWS S3 and other services. Either pass valid region or enable permission for `GetBucketLocation` API.

If you are using MinIO server with empty region, you can pass `us-east-1` as region to `MinioClient.Builder.region()`. For other servers, it is a server problem.

**Comment by harshavardhana** [comment]
It is servers responsibility to ignore any region if it expects region to be `empty`
