### ISSUE TITLE
"A timeout occurred while trying to lock a resource, please reduce your request rate" when trying list objects

### ISSUE THREAD

**Issue by itzhoujun** [minio/minio-java#1353]
code:
```
public void test() throws Exception {
        log.info("start test object list");
        long start = System.currentTimeMillis();
        int count = this.listAll("");
        log.info("test object list complete, spend: {}s, count: {}", (System.currentTimeMillis() - start) / 1000, count);
    }

    private int listAll(String prefix) {
        int count = 0;
        Iterable<Result<Item>> parts = minioClient.listObjects(ListObjectsArgs.builder()
                .prefix(prefix)
                .bucket("test")
                .recursive(true)
                .build());
        Iterator<Result<Item>> iterator = parts.iterator();
        while (iterator.hasNext()) {
            try {
                iterator.next().get();
                count++;
            } catch (Exception e) {
                log.info("list object error: {}", e.getMessage(), e);
            }
        }
        return count;
    }
```
console log:
```
2022-08-09 21:26:03.047  INFO 68233 --- [   scheduling-1] com.kv.service.TestService            : list object error: A timeout occurred while trying to lock a resource, please reduce your request rate

io.minio.errors.ErrorResponseException: A timeout occurred while trying to lock a resource, please reduce your request rate
	at io.minio.S3Base$1.onResponse(S3Base.java:690) ~[minio-8.4.2.jar:8.4.2]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.10.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_312]

2022-08-09 21:26:03.047  INFO 68233 --- [   scheduling-1] com.kv.service.TestService            : test object list complete, spend: 10s, count: 2000
```

**Comment by balamurugana** [comment]
Your S3 service returns the error. If you're using MinIO server, open this issue on the server.
