### ISSUE TITLE
Can't initialize minioClient in quarkus

### ISSUE THREAD

**Issue by Archsx** [minio/minio-java#1406]
I'm using `quarkus` and `kotlin`,  when following the docs(https://min.io/docs/minio/linux/developers/java/minio-java.html), I got a error:
```
 java.lang.ExceptionInInitializerError
        at io.minio.MinioClient$Builder.<init>(MinioClient.java:2447)
        at io.minio.MinioClient.builder(MinioClient.java:2439)
```
## Expected Behavior
work as the docs shows

## Current Behavior

Error above.

## Context

the code is very simple .
```
@ApplicationScoped
@Path("/api")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class UploadResource {
  

    @GET
    @Path("/presignedUrl")
    @PermitAll
    @ReactiveTransactional
    fun getPresignedUrl(fileName: String?): Uni<MyResponse<String>> {
        if (fileName != null) {

            var minioClient =
                MinioClient.builder()
                    .endpoint("https://play.min.io")
                    .credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
                    .build()

            var url: String =
                minioClient.getPresignedObjectUrl(
                   // ...                       
                )
  
        } else {

        }
    }
}



```

**Comment by balamurugana** [comment]
` java.lang.ExceptionInInitializerError` means there was an exception occurred in the static block. You would need to check what exception actually caused  `ExceptionInInitializerError`

**Comment by balamurugana** [comment]
Below code works for me. It seems you have local issue
```kotlin
import io.minio.MinioClient
import io.minio.BucketExistsArgs

fun main() {
    var minioClient = MinioClient.builder().endpoint("https://play.min.io").credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG").build()
    var found = minioClient.bucketExists(BucketExistsArgs.builder().bucket("test").build())
    println("test $found")
}
```
