### ISSUE TITLE
Can minio-java modify the metadata of existing objects ?

### ISSUE THREAD

**Issue by zuihou** [minio/minio-java#1424]
Can [minio-java](https://github.com/minio/minio-java) modify the metadata of existing objects ?

When uploading an object, metadata is not set. Can you modify it after uploading successfully?

**Comment by zuihou** [comment]
1.  When uploading, there is no setting "Content-Disposition" 

2. What method can I set this property after uploading successfully

<img width="2292" alt="image" src="https://user-images.githubusercontent.com/8500410/218695146-6056e44e-881e-4df4-902e-4478f6620319.png">

**Comment by balamurugana** [comment]
You could use [copyObject()](https://minio-java.min.io/io/minio/MinioAsyncClient.html#copyObject-io.minio.CopyObjectArgs-)

**Comment by zuihou** [comment]
```
        String bucket = "dev";
        String key = "123.pdf";

        Map<String, String> map = new HashMap<>();
        map.put("Content-Disposition", "attachment;filename=" + URLEncoder.encode("!@#$%^&*()123中文.pdf", "UTF-8").replaceAll("\\+", "%20"));
        Map<String, String> map2 = new HashMap<>();
        map2.put("aaa", "aadd");

        CopyObjectArgs arg = CopyObjectArgs.builder()
                .source(CopySource.builder()
                        .bucket(bucket)
                        .object(key)
                        .build())
                .bucket(bucket)
                .object( key)
                .userMetadata(map2)
                .headers(map)
//                .tags(Tags.newBucketTags(map2))
                .build();
        conn.copyObject(arg);
```


```
Exception in thread "main" error occurred
ErrorResponse(code = InvalidRequest, message = This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes., bucketName = dev, objectName = 123.pdf, resource = /dev/123.pdf, requestId = 1743DE27CA9E0DAF, hostId = f70b1a07-3235-465e-a229-60ca8281e101)
request={method=PUT, url=http://172.26.3.230:9000/dev/123.pdf, headers=x-amz-meta-aaa: aadd
x-amz-copy-source: /dev/123.pdf
Content-Disposition: attachment;filename=%21%40%23%24%25%5E%26*%28%29%E9%98%BF%E9%87%8CJava%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%20%20%E6%B3%B0%E5%B1%B1%E7%89%88123.pdf
Host: 172.26.3.230:9000
Accept-Encoding: identity
User-Agent: MinIO (Mac OS X; x86_64) minio-java/8.5.1
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20230215T022228Z
Authorization: ██
}
response={code=400, headers=Connection: close
Content-Length: 459
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 15 Feb 2023 02:22:28 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1743DE27CA9E0DAF
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
}

	at io.minio.S3Base$1.onResponse(S3Base.java:690)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by balamurugana** [comment]
An example
```java
import io.minio.CopyObjectArgs;
import io.minio.CopySource;
import io.minio.Directive;
import io.minio.MinioClient;
import io.minio.PutObjectArgs;
import io.minio.StatObjectArgs;
import io.minio.StatObjectResponse;
import java.io.ByteArrayInputStream;
import java.util.HashMap;
import java.util.Map;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioClient minioClient =
        MinioClient.builder()
            .endpoint("https://play.min.io")
            .credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
            .build();

    {
      Map<String, String> headers = new HashMap<>();
      headers.put("Content-Disposition", "attachment; filename=Check.java");

      Map<String, String> userMetadata = new HashMap<>();
      userMetadata.put("My-Project", "Project One");

      ByteArrayInputStream bais = new ByteArrayInputStream("hello, world".getBytes("UTF-8"));
      minioClient.putObject(
          PutObjectArgs.builder().bucket("issue-1424").object("my-objectname").stream(
                  bais, bais.available(), -1)
              .headers(headers)
              .userMetadata(userMetadata)
              .build());
      bais.close();
      System.out.println("new object created");
    }

    // minioClient.traceOn(System.out);

    Map<String, String> headers = new HashMap<>();
    headers.put("Content-Disposition", "attachment; filename=Demo.java");

    Map<String, String> userMetadata = new HashMap<>();
    userMetadata.put("My-Project", "Project Two");

    minioClient.copyObject(
        CopyObjectArgs.builder()
            .bucket("issue-1424")
            .object("my-objectname")
            .source(CopySource.builder().bucket("issue-1424").object("my-objectname").build())
            .headers(headers)
            .userMetadata(userMetadata)
            .metadataDirective(Directive.REPLACE)
            .build());
    System.out.println("metadata updated");

    StatObjectResponse stat =
        minioClient.statObject(
            StatObjectArgs.builder().bucket("issue-1424").object("my-objectname").build());
    System.out.println(stat);
  }
}
```

**Comment by zuihou** [comment]
3q，   add this code  `.metadataDirective(Directive.REPLACE)`,  solved the problem .
