### ISSUE TITLE
uploadPartAsync Broken pipe (Write failed)

### ISSUE THREAD

**Issue by knightdreams6** [minio/minio-java#1466]
I called the uploadPartAsync method in MinioAsyncClient and it always throws the following exception.

java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at okio.OutputStreamSink.write(JvmOkio.kt:53)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
	at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:203)
	at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:57)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

<img width="1152" alt="截屏2023-07-01 18 47 14" src="https://github.com/minio/minio-java/assets/34333488/9172279e-62ec-4675-8ecf-c734b4127af4">

**Comment by balamurugana** [comment]
Check your server why it is closing connection abruptly.

**Comment by knightdreams6** [comment]
The image I use locally has no special configuration

https://hub.docker.com/r/minio/minio

**Comment by balamurugana** [comment]
Please check your network configuration in server and client side.

**Comment by knightdreams6** [comment]
But I can upload successfully by calling MinioAsyncClient#putObject


<img width="1182" alt="截屏2023-07-01 20 50 06" src="https://github.com/minio/minio-java/assets/34333488/84896e87-e8ef-4c79-bca5-7311c02e385c">

**Comment by balamurugana** [comment]
If you are able to do `putObject` of > 5MiB, there is no issue with `uploadPartAsync`, but you want to use low level APIs, refer https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html

**Comment by knightdreams6** [comment]
I want to implement multipart upload function

1. initiateMultipartUpload
2. uploadPart
3. completeMultipartUpload

Should I replace the second step with putObject? But there is no partNumber in PutObjectBaseArgs

**Comment by knightdreams6** [comment]
my problem is solved. The objectName when uploading fragments must be the same as when uploading fragments. The unclear error message has troubled me for a long time. 
Thank you for your reply.
