### ISSUE TITLE
Not able to download file when provided with a path

### ISSUE THREAD

**Issue by ameyakale603** [minio/minio-java#1478]
Below error is thrown when I try to provide a path to the filename in the following code,
`minioClient.downloadObject(
                DownloadObjectArgs.builder()
                        .bucket(bucketName)
                        .object(objectName)
                        .filename(fileName)
                        .build());` where `fileName` looks like `String fileName = basePath+objectName;`
Error
`at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
at io.minio.MinioAsyncClient.downloadObject(MinioAsyncClient.java:269)
at io.minio.MinioAsyncClient.lambda$downloadObject$1(MinioAsyncClient.java:327)
at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
at io.minio.S3Base$1.onResponse(S3Base.java:559)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by balamurugana** [comment]
What is the error?

**Comment by ameyakale603** [comment]
java.nio.file.NoSuchFileException

**Comment by balamurugana** [comment]
In this `String fileName = basePath+objectName`, the path must be exist in your system. e.g. if `fileName = "/tmp" + "path/to/my/object"`, you should have `/tmp/path/to/my/` exist.

**Comment by AYoungProgrammer1** [comment]
111
