### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by Sandm-HY** [minio/minio-java#1487]
Introduce the 8.5.5 version of minio through maven and report an error: 
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okhttp3.RequestBody$Companion.create(RequestBody.kt)
	at okhttp3.RequestBody.create(RequestBody.kt)
	at io.minio.S3Base.<clinit>(S3Base.java:105)
	at io.minio.MinioClient$Builder.<init>(MinioClient.java:2462)
	at io.minio.MinioClient.builder(MinioClient.java:2454)
The code shows that it is a problem with MinioClient.builder(). How can I correct this problem? Is it a dependency conflict?

**Comment by balamurugana** [comment]
Either you have partial okhttp package, you blacklisted some classes, conflicting dependencies or local issue.

**Comment by Sandm-HY** [comment]
Hello, I checked the version problem and resolved the conflicts in order according to the conflicts specified by the maven helper. It showed that there were no conflicts, but the program still reported the following error during initialization:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.minio.MinioAsyncClient
	at io.minio.MinioClient$Builder.<init>(MinioClient.java:2462)
	at io.minio.MinioClient.builder(MinioClient.java:2454)
```

The relevant versions are as follows： `minio:8.5.5 ,  kotlin-stdlib 1.6.20 , okhttp 4.11.0 , okio 3.2.0 `
The initialization statement is：
```
MinioClient minioClient =
                MinioClient.builder()
                        .endpoint("xx")
                        .credentials("xx", "xx")
                        .build();
```

**Comment by balamurugana** [comment]
As I mentioned above you may have partial package installed, blacklisted some classes, conflicting dependencies or local issue. As we test `minio-java` on every PR, it is purely your local issues.  For complete depedencies of `minio-java`, refer https://github.com/minio/minio-java/blob/master/build.gradle
