### ISSUE TITLE
Cannot get STS by Service Account

### ISSUE THREAD

**Issue by supery-chen** [minio/minio-java#1502]
**MinIO Version** 
```sh
minio version RELEASE.2023-10-16T04-13-43Z (commit-id=edfb310a59edb6f1b645fc456b03dfcea770e1b4)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

**SDK Version**
```xml
<dependency>
    <groupId>io.minio</groupId>
    <artifactId>minio</artifactId>
    <version>8.5.6</version>
</dependency>
```

**Java Code**
```java

Provider provider =
        new AssumeRoleProvider(
                Constants.MINIO_ENDPOINT, // STS endpoint usually point to MinIO server.
                "xxxxxxxxxxxxxxxxx", // Access key.
                "yyyyyyyyyyyyyyyyyyyyyyyyyyyyy", // Secret key.
                2000, // Duration seconds if available.
                null, // Policy if available.
                null, // Region if available.
                null, // Role ARN if available.
                null, // Role session name if available.
                null, // External ID if available.
                null);
Credentials credentials = provider.fetch();
```

**Exception**
```
Exception in thread "main" java.security.ProviderException: STS service failed with HTTP status code 403
	at io.minio.credentials.AssumeRoleBaseProvider.fetch(AssumeRoleBaseProvider.java:85)
	at com.superychen.minio.demo.examples.GetStsToken.main(GetStsToken.java:31)
```

---

I create a new user named `sts`，then create a Service Account for sts，`xxxxxxxxxxxxxxxxx` is the Access Key.
Now I can get STS by username `sts` and password，but cannot get STS by Access Key xxxxxxxxxxxxxxxxx.

**Comment by balamurugana** [comment]
As server returns an error, you would need to check your STS server/service

**Comment by harshavardhana** [comment]
STS and Service Accounts are leaf accounts you can't use them to generate more temporary credentials.

**Comment by supery-chen** [comment]
> STS and Service Accounts are leaf accounts you can't use them to generate more temporary credentials.

Thanks!
