### ISSUE TITLE
 Broken pipe

### ISSUE THREAD

**Issue by qqhai007** [minio/minio-java#1526]
linux  upload file  to  windows minio server

java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831) ~[na:na]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1304) ~[na:na]
	at okio.OutputStreamSink.write(JvmOkio.kt:57) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.RealBufferedSink.write(RealBufferedSink.kt:146) ~[okio-jvm-3.0.0.jar!/:na]
	at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271) ~[okhttp-4.10.0.jar!/:na]
	at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[okio-jvm-3.0.0.jar!/:na]
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218) ~[okhttp-4.10.0.jar!/:na]
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.RealBufferedSink.write(RealBufferedSink.kt:203) ~[okio-jvm-3.0.0.jar!/:na]
	at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:57) ~[minio-8.4.3.jar!/:8.4.3]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.10.0.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

**Comment by balamurugana** [comment]
This means the server closed the connection. Please check your server!
