### ISSUE TITLE
Last Minio Java SDK Client is not compatible with last minio tenant created from operator

### ISSUE THREAD

**Issue by masalinas** [minio/minio-java#1533]
I install the minio tenant `Version: 2024-02-17T01:15:57Z`. I can connect and manage this tenant with the mc CLI and with the last python sdk client, but not with the last java SDK Client version 8.5.2. I obtain always this error when try to list buckets or exectue any method:

```
Caused by: io.minio.errors.InvalidResponseException: Non-XML response from server. Response code: 400, Content-Type: null, body: Client sent an HTTP request to an HTTPS server.

	at io.minio.S3Base$1.onResponse(S3Base.java:595) ~[minio-8.5.2.jar:8.5.2]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
The Minio Java SDK client version is: 8.5.2 using JDK 17 in springboot 3.2.2

I tested the code **with` https://play.min.io` and works ok but not with my own minio tenant** created with the last minio operator in my kubernetes cluster.

Where is the problem?, this java SDK is compatible with the minio tenant version 2024-02-17T01:15:57Z?

**Comment by masalinas** [comment]
Finally I discover that the correct configuration for my case when the certificate is autoasigned is that:

```
        MinioClient client = MinioClient.builder()
        	.endpoint(endpoint, port, secure)
                .credentials(accessKey, secretKey)                
                .build();

        client.ignoreCertCheck();
```
        
        
        
Where 

```
endpoint: localhost
port: 9000
secure: true
accessKey: MY_ACCESS_KEY
secretKey: MY_SECRET_KEY      
```    
           
And executed the method ignoreCertCheck to ignore the autosigned certificates. Now works ok
