### ISSUE TITLE
Getting "Unsupported OkHttp library found." Error

### ISSUE THREAD

**Issue by subbula1979** [minio/minio-java#1541]
I have a spark Job and I am trying to upload a zip file to Minio Bucket. 

When I try to initialize the Minio Client, using the code below, I am getting the below error while running the job in k8s .

private val minioClient = MinioClient.builder().endpoint(minioHost).credentials(accessKey, secretKey).build();

RunTime Error:
 Caused by: java.lang.RuntimeException: Unsupported OkHttp library found. Must use okhttp >= 4.11.0
   at io.minio.S3Base.<clinit>(S3Base.java:107)
    ... 41 more
Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'
    at io.minio.S3Base.<clinit>(S3Base.java:105)

Following are my gradle entries
implementation group: 'io.minio', name: 'minio', version: '8.5.9'
 compileOnly 'com.squareup.okhttp3:okhttp:4.12.0'

Though I included the latest build for "okhttp", I am  still getting the RunTime Exception. Please suggest ways to fix this issue.

**Comment by harshavardhana** [comment]
You need to build your project with proper okhttp3 dependencies. This is unrelated to this project.
