### ISSUE TITLE
Unexpected char 0x0a at 58 in Authorization value

### ISSUE THREAD

**Issue by TOTHT0MI** [minio/minio-java#1565]
I'm using minio-java with Spring. I've faced an issue with
```
java.lang.IllegalArgumentException: Unexpected char 0x0a at 58 in Authorization value
	at okhttp3.Headers$Companion.checkValue(Headers.kt:450) ~[okhttp-4.12.0.jar:na]
	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362) ~[okhttp-4.12.0.jar:na]
	at okhttp3.Headers$Builder.set(Headers.kt:344) ~[okhttp-4.12.0.jar:na]
	at okhttp3.Request$Builder.header(Request.kt:199) ~[okhttp-4.12.0.jar:na]
	at io.minio.Signer.signV4(Signer.java:297) ~[minio-8.5.10.jar:8.5.10]
	at io.minio.Signer.signV4S3(Signer.java:304) ~[minio-8.5.10.jar:8.5.10]
	at io.minio.S3Base.executeAsync(S3Base.java:584) ~[minio-8.5.10.jar:8.5.10]
	at io.minio.S3Base.lambda$putObjectAsync$26(S3Base.java:2988) ~[minio-8.5.10.jar:8.5.10]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[na:na]
	at io.minio.S3Base$1.onResponse(S3Base.java:644) ~[minio-8.5.10.jar:8.5.10]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

```
Now the lines here (due to Kotlin) are a bit off. I assume the issue is Signer class line 136. For some reason it adds an LF?

My versions:
kotlin 2.0.0
minio-java - 8.5.10
spring-boot - 3.3.0
(I've checked they use the same okhttp version, so it should not be caused by these two in the same environment, yet I didn't test the minio client standalone)

This is my initialization, as you can see I've attempted to trim, because I suspected it could be related to the keys. But then I saw the source and the fact that authorization is a bit more involved, than I thought.
```kotlin
// this is a Bean function, don't mind the return

val client = MinioClient.builder()
            .endpoint(endpoint.trim())
            .credentials(accessKey.trim(), secretKey.trim())
            .build()
return S3StorageProvider(client, bucketName.trim())
```

The actual function I call:
```kotlin
try {
    val key = filePath.toKey()
    val fileSize = Files.size(tempFile)
    val args = PutObjectArgs.builder()
        .bucket(bucket)
        .`object`(key)
        .contentType(MediaType.APPLICATION_OCTET_STREAM_VALUE)
        .stream(tempFile.inputStream(), fileSize, -1)
        .build()

    s3.putObject(args)
} catch (e: Exception) {
    throw RuntimeException("S3 Storage Provider failed with exception", e)
}
```

In my case a key is a big path, something like `{uuid}/{uuid}/{uuid}.pdf`, but I've tried it with hard coding `test.pdf` there, and also without extension, because first I could not figure out what is related to the issue and what is not.

I've tried everything on my side, but I can't seem to fix it. I really don't feel like going to AWS SDK, because I couldn't really get it to work with 3rd party S3 compatible servers.

**Comment by balamurugana** [comment]
Below is the logic to construct `Authorization` header.

```java
    this.authorization =
        "AWS4-HMAC-SHA256 Credential="
            + this.accessKey
            + "/"
            + this.scope
            + ", SignedHeaders="
            + this.signedHeaders
            + ", Signature="
            + this.signature;
```

I suspect you have invalid character in access key and/or headers. Please check those values.

**Comment by balamurugana** [comment]
It is purely your local problem. I guess wrong arguments are supplied to `minio-java` APIs.
