### ISSUE TITLE
upload file fail. but small size file ok

### ISSUE THREAD

**Issue by skydream-xu** [minio/minio-java#1572]
Upload a big file which may be larger than 100 KB, It can't work; but if the file is very small which may be smaller than 10 KB，it works well, I don't know why?
the main code as follow:
        MinioClient minioClient = MinioClient.builder()
//                        .endpoint(minioProperties.getIp(),minioProperties.getPort(),minioProperties.getSecure())
                .endpoint("http:" + minioProperties.getIp() , minioProperties.getPort(),  false)
                .credentials(minioProperties.getAccessKey(), minioProperties.getSecretKey())
                .build();
        this.minioClient = minioClient;

        InputStream inputStream = file.getInputStream();
        long size = file.getSize();
        String contentType = file.getContentType();

        // Upload known sized input stream.
        minioClient.traceOn(System.out);
        minioClient.putObject(
                PutObjectArgs.builder()
                        .bucket(bucketName) 
                        .object(minioFilename)
                        .stream(inputStream, size, -1)
                        .contentType(contentType) 
                        .build());

minio jar mave :
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>8.0.3</version>
            </dependency>

error info:
---------START-HTTP---------
PUT /xhb/adb41f9c-d7af-4fe4-82a1-cd173272231f_log.txt HTTP/1.1
Content-Type: text
Host: 10.51.16.125:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 11; amd64) minio-java/8.0.3
Content-MD5: N4CugMs9Pp42QVHJXzcOfQ==
x-amz-content-sha256: 4beefe3692462d759ab9c2fdedbe9c8e04f10361d8da73db79c1ee1c939ff709
x-amz-date: 20240626T071739Z
Authorization: ██

java.net.SocketException: 拒绝访问。

	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
	at okio.OutputStreamSink.write(JvmOkio.kt:56)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:102)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:256)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:147)
	at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:279)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:223)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:256)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:204)
	at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:78)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.minio.MinioClient.execute(MinioClient.java:647)
	at io.minio.MinioClient.putObject(MinioClient.java:4547)
	at io.minio.MinioClient.putObject(MinioClient.java:2713)
	at io.minio.MinioClient.putObject(MinioClient.java:2830)
	at com.example.demo.MinioFileUtil.uploadFile(MinioFileUtil.java:417)
	at com.example.demo.DemoApplicationTests.uploadFile(DemoApplicationTests.java:184)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.io.IOException: unexpected end of stream on http://10.51.16.125:9000/...
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
		... 20 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:335)
		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
		... 22 more

**Comment by balamurugana** [comment]
1. Use the latest version of `minio-java`
2. Check whether you are passing correct/existing file

**Comment by skydream-xu** [comment]
> 1. Use the latest version of `minio-java`
> 2. Check whether you are passing correct/existing file

I just test the newest minio jar which version is 8.5.11 , but there is still the problem . And I am sure that the file is existing in my location disk, not in the minio bucket . Please note that the small size file is ok .

**Comment by balamurugana** [comment]
All PRs to `minio-java` is tested on MS Windows as well by Github workflow. You have local issues, nothing can be done here.

**Comment by rainermaechtig** [comment]
Maybe the bucket has a retention period. The current implementation only sets a  header "x-amz-content-sha256" for multipart uploads but no "Content-MD5".

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html#object-lock-put-object
