### ISSUE TITLE
ComposeObject fails with IllegalArgumentException

### ISSUE THREAD

**Issue by dst-post** [minio/minio-java#1577]
For a project I am working on I have to combine a lot of resources stored on Minio into a single file. I tried to do this using ComposeObject, but I get an IllegalArgumentException "size 400 must be greater than 5242880". 
The 400 is the size of the first object in my ComposeSources, changing the first object to something else just changes the size in the error. 

I recreated this using the https://github.com/minio/minio-java/blob/release/examples/ComposeObject.java example, only changing access keys, buckets and object keys, but this has the same result. So i think something is broken inside ComposeObject.

`> Task :MinioComposeObject.main()
Exception in thread "main" java.lang.IllegalArgumentException: source afp-fragments/019135f3-3ae5-74be-99de-c31b13589198/019135f9-135e-7db9-91d2-d7afea46b340: size 1272 must be greater than 5242880
	at io.minio.S3Base.lambda$calculatePartCountAsync$7(S3Base.java:1190)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.minio.S3Base$1.onResponse(S3Base.java:644)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

I am using Java 21 and io.minio:minio version 8.5.11. 

Or am I missing something and ComposeObject is only supported for stored objects larger than the MIN_MULTIPART_SIZE?

**Comment by balamurugana** [comment]
@dst-post `ComposeObject` uses various multipart upload API calls i.e. As per S3 specification, each part (here object size) must be `>= MIN_MULTIPART_SIZE` except last part.

**Comment by dst-post** [comment]
One last comment: It would be great if this would be mentionend in the documentation to https://min.io/docs/minio/linux/developers/java/API.html#composeObject since there is no mention of multipart API calls and such limitations.

**Comment by balamurugana** [comment]
@dst-post It is not required. It is expected to know S3 specification to use this SDK.
