### ISSUE TITLE
Stream closed during snowball obejct upload

### ISSUE THREAD

**Issue by Francesko90** [minio/minio-java#1582]
Hello

I'm trying to upload a big file (16 GB) with snowball object API, this is my code

```
public static void main(String[] args)
      throws ServerException, InsufficientDataException, ErrorResponseException, IOException, NoSuchAlgorithmException, InvalidKeyException, InvalidResponseException, XmlParserException, InternalException {
    MinioClient minioClient = MinioClient.builder().endpoint("http://172.16.1.15:9000")
        .credentials("minio", "minio")
        .build();
    minioClient.traceOn(System.out);
    if (!minioClient.bucketExists(BucketExistsArgs.builder().bucket("ada").build())) {
      minioClient.makeBucket(MakeBucketArgs.builder().bucket("ada").build());
    }

    Path TEMP_DIRECTORY = new File(System.getProperty("java.io.tmpdir")).toPath().resolve("sftp");

    try (Stream<Path> paths = Files.walk(TEMP_DIRECTORY)) {
      List<File> files = paths
          .filter(Files::isRegularFile).map(Path::toFile).collect(Collectors.toList());
      List<SnowballObject> objects = new ArrayList<>();
      int count = 0;
      for (File file : files) {
        objects.add(new SnowballObject(file.getName(), file.toPath().toString()));

        count++;
        if (count > 100) {
          break;
        }
      }
      minioClient.uploadSnowballObjects(
          UploadSnowballObjectsArgs.builder().compression(true)
              .stagingFilename("C:\\Users\\name\\Desktop\\temp.tar").bucket("ada")
              .objects(objects).build());
    } catch (IOException e) {
      e.printStackTrace();
    }
```

The zip folder is created correctly but after the PUT request the java code crash with stream closed error

```
---------START-HTTP---------
GET /ada?location= HTTP/1.1
Host: 192.168.1.15:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 11; amd64) minio-java/8.5.12
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20240916T072442Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 128
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 17F5A8AA67838399
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 2432
X-Ratelimit-Remaining: 2432
X-Xss-Protection: 1; mode=block
Date: Mon, 16 Sep 2024 07:24:42 GMT

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
HEAD /ada HTTP/1.1
Host: 192.168.1.15:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 11; amd64) minio-java/8.5.12
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20240916T072442Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 0
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 17F5A8AA75C186DB
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 2432
X-Ratelimit-Remaining: 2432
X-Xss-Protection: 1; mode=block
Date: Mon, 16 Sep 2024 07:24:42 GMT


----------END-HTTP----------
---------START-HTTP---------
PUT /ada/snowball.5846518567356468807.tar HTTP/1.1
X-Amz-Meta-Snowball-Auto-Extract: true
Host: 192.168.1.15:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 11; amd64) minio-java/8.5.12
x-amz-content-sha256: 28dc6dd0e4cc1c9565e7bb023c8c1ba56556c872fcf3c29f84295639a05330de
x-amz-date: 20240916T072504Z
Authorization: ██

java.io.IOException: Stream Closed
	at java.base/java.io.RandomAccessFile.seek0(Native Method)
	at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
	at io.minio.PartSource.source(PartSource.java:88)
	at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:57)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Disconnected from the target VM, address: '127.0.0.1:62656', transport: 'socket'

Process finished with exit code 0

```

I tried with small zip like 1.7GB but the error is the same, I tried with single file and works fine. 
I tried with another server deployed locally with minio but the error is the same

JDK 18: semeru-18.0.2
MinIO client: 8.5.12

**Comment by klauspost** [comment]
Check your logs and your various timeouts. Capture `mc admin trace -v ALIAS` of the upload.

MinIO should not terminate the upload without returning an error, so it is unlikely the MinIO server.

You can try with `X-Amz-Meta-Minio-Snowball-Ignore-Errors: true`, but I doubt it will make a difference.

**Comment by Francesko90** [comment]
Thank you @balamurugana! 

You are right! I tried to open manually the tar generated by the minio library and window give me strange error.
I tried on linux, instestead of window, but I have the same error
Now I removed the stagingFIleName from args builder and works correctly!

```
UploadSnowballObjectsArgs.builder().compression(true).objects(objects).build());
```

instead 
```

UploadSnowballObjectsArgs.builder().compression(true)
 .stagingFilename("C:\\Users\\name\\Desktop\\temp.tar").bucket("ada")
 .objects(objects).build());
```

But at the first iteration I have received an heap space exception

`java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space`

So my question is "Is the archive saved in memory if I dont' specify the stagingFIleName arg?"

**Comment by balamurugana** [comment]
@Francesko90 If staging file is not provided, we have to create tarball in memory, it is obvious to lead OOM for source files.

**Comment by Francesko90** [comment]
@balamurugana I tried with your solution



> @Francesko90 It looks like some MS Windows error at `seek` syscall.
> 
> ```
> java.io.IOException: Stream Closed
> 	at java.base/java.io.RandomAccessFile.seek0(Native Method)
> 	at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
> 	at io.minio.PartSource.source(PartSource.java:88)
> ```
> 
> I guess the tarball creation doesn't sync to the disk completely before hitting snowball upload. You could try to create a tarball separately, then try to upload the file as single part with `putObject` and header `headers.put("X-Amz-Meta-Snowball-Auto-Extract", "true");` using `minio-java`.

I tried with your solution but the archive is not extracted by minio

```
      Map<String, String> headers = new HashMap<>();
      headers.put("X-Amz-Meta-Snowball-Auto-Extract", "true");

      minioClient.putObject(
          PutObjectArgs.builder().bucket("ada").object(tar.getName()).stream(
                  new FileInputStream(tar), tar.length(), -1).headers(headers)
              .build());
```

I tried with headers and extraHeaders

**Comment by balamurugana** [comment]
@Francesko90 You would need to set part size as `tar.length()` instead of `-1` for snowball upload i.e. multipart upload doesn't work for snowball upload.

**Comment by Francesko90** [comment]
Unfortunately the size it's over 5GB so it's not possibile upload without multipart

**Comment by balamurugana** [comment]
I don't think you are allowed to use > 5GiB tar as snowball
