### ISSUE TITLE
Thread Leak when calling MinioClient.close()

### ISSUE THREAD

**Issue by dadoonet** [minio/minio-java#1583]
Hey team,

I have a curious behaviour. I'm using [RandomizedTesting framework](http://labs.carrotsearch.com/randomizedtesting.html) for my tests. It detects automatically ZombieThreads.

So I have this test:

```java
@RunWith(RandomizedRunner.class)
@TimeoutSuite(millis = 5 * 60 * 1000)
@ThreadLeakScope(ThreadLeakScope.Scope.SUITE)
@ThreadLeakLingering(linger = 10000) // 5 sec lingering
public class ZombieDemoIT {

    @Test(expected = java.net.ConnectException.class)
    public void testZombie() throws Exception {
        System.out.println("Starting Minio Client");
        MinioClient minioClient = MinioClient.builder()
                .endpoint("http://localhost:8080")
                .credentials("foo", "bar")
                .build();

        minioClient.bucketExists(BucketExistsArgs.builder().bucket("foo").build());
        minioClient.close();
    }
}
```

I don't start Minio on my machine, so the code throws an expected `ConnectException`. All good.

But then, RandomizedTesting framework checks for the remaining threads. And here is what is happening:

```
Starting Minio Client
sept. 16, 2024 3:27:25 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
WARNING: Will linger awaiting termination of 1 leaked thread(s).
sept. 16, 2024 3:27:35 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
SEVERE: 1 thread leaked from SUITE scope at fr.pilato.test.zombie.ZombieDemoIT: 
   1) Thread[id=33, name=OkHttp Dispatcher, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
sept. 16, 2024 3:27:35 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
INFO: Starting to interrupt leaked threads:
   1) Thread[id=33, name=OkHttp Dispatcher, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
sept. 16, 2024 3:27:37 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
SEVERE: There are still zombie threads that couldn't be terminated:
   1) Thread[id=33, name=OkHttp Dispatcher, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at fr.pilato.test.zombie.ZombieDemoIT: 
   1) Thread[id=33, name=OkHttp Dispatcher, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

	at __randomizedtesting.SeedInfo.seed([E6A0362116704881]:0)


com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   1) Thread[id=33, name=OkHttp Dispatcher, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

	at __randomizedtesting.SeedInfo.seed([E6A0362116704881]:0)


Process finished with exit code 255
```

As you can see, some OkHttp are still running even though I called `minioClient.close()`.

I did another experiment with `try-with-resources`:

```java
@RunWith(RandomizedRunner.class)
@TimeoutSuite(millis = 5 * 60 * 1000)
@ThreadLeakScope(ThreadLeakScope.Scope.SUITE)
@ThreadLeakLingering(linger = 10000) // 5 sec lingering
public class NoZombieDemoIT {

    @Test(expected = java.net.ConnectException.class)
    public void testZombie() throws Exception {
        System.out.println("Starting Minio Client");
        try (MinioClient minioClient = MinioClient.builder()
                .endpoint("http://localhost:8080")
                .credentials("foo", "bar")
                .build()) {
            minioClient.bucketExists(BucketExistsArgs.builder().bucket("foo").build());
        }
    }
}
```

This time, I'm not calling explicitly `close()` as it's done automatically after the `try` block.
And this time, everything works well. All the threads are closed.

```
Starting Minio Client

Process finished with exit code 0
```

Do you know what should I call to actually close all the underlying resources started by the minio client?

I shared a full demo of this at https://github.com/dadoonet/demo-ssh-mino

**Comment by dadoonet** [comment]
My bad. It was a stupid bug made by the person between the chait and the keyboard, aka me!
