### ISSUE TITLE
Thread Leak when calling MinioClient.close()

### ISSUE THREAD

**Issue by dadoonet** [minio/minio-java#1584]
Hey team,

I have a curious behaviour. I'm using [RandomizedTesting framework](http://labs.carrotsearch.com/randomizedtesting.html) for my tests. It detects automatically ZombieThreads:

```java
@RunWith(RandomizedRunner.class)
@ThreadLeakScope(ThreadLeakScope.Scope.SUITE)
@ThreadLeakLingering(linger = 200) // 200 ms lingering
public class ZombieDemoIT {

    @Test
    public void testZombie() throws Exception {
        try (MinioClient minioClient = MinioClient.builder()
                .endpoint("http://127.0.0.1:9000")
                .credentials("minioadmin", "minioadmin")
                .build()) {
            System.out.println("Starting Minio Client");
            minioClient.bucketExists(BucketExistsArgs.builder().bucket("foo").build());
        } catch (ConnectException e) {
            System.out.println("You need to start a minio service first:");
            System.out.println("docker run -p 9000:9000 minio/minio server /tmp");
        }
    }
}
```

I don't start Minio on my machine, so the code throws an expected `ConnectException`. All good.

I start a Minio container with:

```sh
 docker run -p 9000:9000 minio/minio server /tmp
```

Then, RandomizedTesting framework checks for the remaining threads. And here is what is happening:

```
Starting Minio Client
sept. 18, 2024 12:04:58 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
WARNING: Will linger awaiting termination of 2 leaked thread(s).
sept. 18, 2024 12:04:58 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
SEVERE: 2 threads leaked from SUITE scope at fr.pilato.test.zombie.minio.ZombieDemoIT: 
   1) Thread[id=33, name=OkHttp TaskRunner, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   2) Thread[id=34, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
        at okio.AsyncTimeout$Companion.awaitTimeout$okio(AsyncTimeout.kt:320)
        at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.kt:186)
sept. 18, 2024 12:04:58 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
INFO: Starting to interrupt leaked threads:
   1) Thread[id=33, name=OkHttp TaskRunner, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
   2) Thread[id=34, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
sept. 18, 2024 12:05:01 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
SEVERE: There are still zombie threads that couldn't be terminated:
   1) Thread[id=33, name=OkHttp TaskRunner, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   2) Thread[id=34, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
        at okio.AsyncTimeout$Companion.awaitTimeout$okio(AsyncTimeout.kt:308)
        at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.kt:186)

com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from SUITE scope at fr.pilato.test.zombie.minio.ZombieDemoIT: 
   1) Thread[id=33, name=OkHttp TaskRunner, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   2) Thread[id=34, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
        at okio.AsyncTimeout$Companion.awaitTimeout$okio(AsyncTimeout.kt:320)
        at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.kt:186)

	at __randomizedtesting.SeedInfo.seed([FF50E1FC370A930E]:0)


com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   1) Thread[id=33, name=OkHttp TaskRunner, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
        at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
        at java.base/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
        at java.base/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
        at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   2) Thread[id=34, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-ZombieDemoIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
        at okio.AsyncTimeout$Companion.awaitTimeout$okio(AsyncTimeout.kt:308)
        at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.kt:186)

	at __randomizedtesting.SeedInfo.seed([FF50E1FC370A930E]:0)


Process finished with exit code 255
```

As you can see, some OkHttp threads are still running even though the call to `minioClient.close()` is automatically done.

Do you know what should I call to actually close all the underlying resources started by the minio client?

I shared a full demo of this at https://github.com/dadoonet/demo-ssh-mino

**Comment by balamurugana** [comment]
@dadoonet The default `httpClient` has one minute timeout after executing 
```
      httpClient.dispatcher().executorService().shutdown();
      httpClient.connectionPool().evictAll();
```

If you are looking a custom timeout or different behavior, you would need to pass `customHttpClient` with appropriate dispatcher and connectionpool.

**Comment by dadoonet** [comment]
@balamurugana Thanks a lot. Indeed I can reproduce the problem by using ohHttpClient only:

```java
@RunWith(RandomizedRunner.class)
@ThreadLeakScope(ThreadLeakScope.Scope.SUITE)
@ThreadLeakLingering(linger = 200) // 200 ms lingering
public class ZombieOkHttpIT {

    @Test
    public void testZombie() throws Exception {
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
                .url("http://127.0.0.1:8080")
                .build();

        try (Response response = client.newCall(request).execute()) {
            System.out.println("response = " + response.body().string());
        } catch (ConnectException e) {
            System.out.println("You need to start a minio service first:");
            System.out.println("docker run -p 8080:80 httpd");
        }
    }
}
```


So it's not related to the Minio java client.
