### ISSUE TITLE
Unexpected behavior of statObject() in MinioAsyncClient

### ISSUE THREAD

**Issue by insotriplesix** [minio/minio-java#1588]
Hi,

I seem to have encountered strange behavior with Kotlin (Coroutines?) and `MinioAsyncClient`. 
Here are the sources of an example project:

`MinioTest.kt`:
```kotlin
package org.example

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe
import io.minio.GetObjectArgs
import io.minio.MinioAsyncClient
import io.minio.StatObjectArgs
import io.minio.errors.ErrorResponseException
import kotlinx.coroutines.future.await

class MinioTest : DescribeSpec() {
    init {
        val client = MinioAsyncClient.builder()
            .endpoint("http://localhost:9000")
            .credentials("minio_user", "minio_password")
            .build()

        describe("describe") {
            val bucketName = "test-bucket"
            val path = "path"

            it("test") {
                suspend fun exCauseCause(): Boolean {
                    val statObjectArgs = StatObjectArgs.builder()
                        .bucket(bucketName)
                        .`object`(path)
                        .build()

                    return try {
                        client.statObject(statObjectArgs).await()
                        true
                    } catch (ex: Exception) {
                        if ((ex.cause!!.cause as? ErrorResponseException)?.errorResponse()?.code() == "NoSuchKey") {
                            false
                        } else {
                            throw ex
                        }
                    }
                }

                suspend fun justEx(): Boolean {
                    val getObjectArgs = GetObjectArgs.builder()
                        .bucket(bucketName)
                        .`object`(path)
                        .build()

                    return try {
                        client.getObject(getObjectArgs).await()
                        true
                    } catch (ex: Exception) {
                        if ((ex as? ErrorResponseException)?.errorResponse()?.code() == "NoSuchKey") {
                            false
                        } else {
                            throw ex
                        }
                    }
                }

                exCauseCause() shouldBe false
                justEx() shouldBe false
            }
        }
    }
}
```

`build.gradle.kts`:
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.8.21"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
    testImplementation("io.kotest:kotest-runner-junit5-jvm:5.9.0")
    testImplementation("io.minio:minio:8.5.12")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1")
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```

When there is no object in a bucket, both functions `exCauseCause()` and `justEx()` throw an exception. But in the first case, I have `CompletionException` caused by `CompletionException` caused by `ErrorResponseException`... So, to get the last one I have to write the somewhat strange `ex.cause!!.cause` (which can be transformed into the more elegant `ex.rootCause`, but still). In the second case, I transform the `ex` immediately. 

If that's correct, could you please explain why the function `statObject` has different behavior? If that's not an issue with `MinioAsyncClient`, I'd be happy to hear that as well and investigate further. If that's a bug, well, that's a bug then

![justEx](https://github.com/user-attachments/assets/8626eaa3-e084-41e7-8aff-7d17562e903d)
![exCauseCause](https://github.com/user-attachments/assets/4584c302-3632-44fe-85ae-c347e132c805)

**Comment by balamurugana** [comment]
I think this issue is unrelated to `minio-java`. Below is an example of `minio-java` behavior with `java`
```java
import io.minio.MinioAsyncClient;
import io.minio.StatObjectArgs;
import io.minio.StatObjectResponse;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioAsyncClient minioClient =
        MinioAsyncClient.builder()
            .endpoint("play.min.io")
            .credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
            .build();
    minioClient.traceOn(System.out);
    StatObjectResponse stat =
        minioClient
            .statObject(StatObjectArgs.builder().bucket("mybucket").object("my-objectname").build())
            .get();
    System.out.println(stat);
  }
}
```

```
$ javac -cp api/build/libs/minio-8.5.13-DEV-all.jar Check.java && java -cp api/build/libs/minio-8.5.13-DEV-all.jar:. Check
---------START-HTTP---------
GET /mybucket?location= HTTP/1.1
Host: play.min.io
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.13-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20241022T013811Z
Authorization: ██

HTTP/1.1 200
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 22 Oct 2024 01:38:13 GMT
Content-Type: application/xml
Content-Length: 137
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1800A2A69D93CDB0
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 1600
X-Ratelimit-Remaining: 1600
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">us-east-1</LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
HEAD /mybucket/my-objectname HTTP/1.1
Host: play.min.io
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.13-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20241022T013813Z
Authorization: ██

HTTP/1.1 404
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 22 Oct 2024 01:38:13 GMT
Content-Length: 0
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1800A2A6BBBCC7B1
X-Content-Type-Options: nosniff
X-Minio-Error-Code: NoSuchKey
X-Minio-Error-Desc: "The specified key does not exist."
X-Ratelimit-Limit: 1600
X-Ratelimit-Remaining: 1600
X-Xss-Protection: 1; mode=block

----------END-HTTP----------
Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: error occurred
ErrorResponse(code = NoSuchKey, message = Object does not exist, bucketName = mybucket, objectName = my-objectname, resource = /mybucket/my-objectname, requestId = 1800A2A6BBBCC7B1, hostId = 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac)
request={method=HEAD, url=https://play.min.io/mybucket/my-objectname, headers=Host: play.min.io
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.13-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20241022T013813Z
Authorization: ██
}
response={code=404, headers=Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 22 Oct 2024 01:38:13 GMT
Content-Length: 0
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1800A2A6BBBCC7B1
X-Content-Type-Options: nosniff
X-Minio-Error-Code: NoSuchKey
X-Minio-Error-Desc: "The specified key does not exist."
X-Ratelimit-Limit: 1600
X-Ratelimit-Remaining: 1600
X-Xss-Protection: 1; mode=block
}

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at Check.main(Check.java:27)
Caused by: java.util.concurrent.CompletionException: error occurred
ErrorResponse(code = NoSuchKey, message = Object does not exist, bucketName = mybucket, objectName = my-objectname, resource = /mybucket/my-objectname, requestId = 1800A2A6BBBCC7B1, hostId = 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac)
request={method=HEAD, url=https://play.min.io/mybucket/my-objectname, headers=Host: play.min.io
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.13-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20241022T013813Z
Authorization: ██
}
response={code=404, headers=Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 22 Oct 2024 01:38:13 GMT
Content-Length: 0
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1800A2A6BBBCC7B1
X-Content-Type-Options: nosniff
X-Minio-Error-Code: NoSuchKey
X-Minio-Error-Desc: "The specified key does not exist."
X-Ratelimit-Limit: 1600
X-Ratelimit-Remaining: 1600
X-Xss-Protection: 1; mode=block
}

	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.minio.S3Base$1.onResponse(S3Base.java:776)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: error occurred
ErrorResponse(code = NoSuchKey, message = Object does not exist, bucketName = mybucket, objectName = my-objectname, resource = /mybucket/my-objectname, requestId = 1800A2A6BBBCC7B1, hostId = 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac)
request={method=HEAD, url=https://play.min.io/mybucket/my-objectname, headers=Host: play.min.io
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.13-DEV
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20241022T013813Z
Authorization: ██
}
response={code=404, headers=Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 22 Oct 2024 01:38:13 GMT
Content-Length: 0
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1800A2A6BBBCC7B1
X-Content-Type-Options: nosniff
X-Minio-Error-Code: NoSuchKey
X-Minio-Error-Desc: "The specified key does not exist."
X-Ratelimit-Limit: 1600
X-Ratelimit-Remaining: 1600
X-Xss-Protection: 1; mode=block
}

	at io.minio.S3Base$1.onResponse(S3Base.java:775)
	... 4 more
```
