### ISSUE TITLE
"Unsupported OkHttp library found. Must use okhttp >= 4.11.0" - Maven project

### ISSUE THREAD

**Issue by timdufrane** [minio/minio-java#1598]
Hello,

I'm having an issue with a Maven project. The relevant pom.xml section is:

```
    <dependency>
      <groupId>io.minio</groupId>
      <artifactId>minio</artifactId>
      <version>8.5.13</version>
      <exclusions>
        <exclusion>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.12.0</version>
    </dependency>
```

Relevant dependency tree section (there are no other instances of okhttp elsewhere):

```
[INFO] +- my.internal.package:storage:jar:2-SNAPSHOT:compile
[INFO] |  +- io.minio:minio:jar:8.5.13:compile
[INFO] |  |  +- com.carrotsearch.thirdparty:simple-xml-safe:jar:2.7.1:compile     
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile  
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.3:compile   
[INFO] |  |  +- org.bouncycastle:bcprov-jdk18on:jar:1.78.1:compile
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.1.10.7:compile
[INFO] |  \- com.squareup.okhttp3:okhttp:jar:4.12.0:compile
[INFO] |     +- com.squareup.okio:okio:jar:3.6.0:compile
[INFO] |     |  \- com.squareup.okio:okio-jvm:jar:3.6.0:compile
[INFO] |     |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.10:compile
[INFO] |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.8.21:compile        
[INFO] |        +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.31:compile
[INFO] |        |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.8.21:compile
```

The relevant exception when attempting to use the client:

```
! java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'
! at okio.Segment.writeTo(Segment.kt:169)
! at okio.Segment.compact(Segment.kt:152)
! at okio.Buffer.write(Buffer.kt:1532)
! at okio.Buffer.read(Buffer.kt:1544)
! at okio.Buffer.writeAll(Buffer.kt:1303)
! at okio.Options$Companion.buildTrieRecursive(Options.kt:189)
! at okio.Options$Companion.buildTrieRecursive(Options.kt:175)
! at okio.Options$Companion.buildTrieRecursive$default(Options.kt:107)
! at okio.Options$Companion.of(Options.kt:72)
! at okhttp3.internal.Util.<clinit>(Util.kt:70)
! at okhttp3.RequestBody$Companion.create(RequestBody.kt:145)
! at okhttp3.RequestBody$Companion.create$default(RequestBody.kt:140)
! at okhttp3.RequestBody$Companion.create(RequestBody.kt)
! at okhttp3.RequestBody.create(RequestBody.kt)
! at io.minio.S3Base.<clinit>(S3Base.java:105)
! ... 74 common frames omitted
! Causing: java.lang.RuntimeException: Unsupported OkHttp library found. Must use okhttp >= 4.11.0
! at io.minio.S3Base.<clinit>(S3Base.java:107)
! ... 74 common frames omitted
! Causing: java.lang.ExceptionInInitializerError: null
! at io.minio.MinioClient$Builder.<init>(MinioClient.java:2469)
! at io.minio.MinioClient.builder(MinioClient.java:2461)
! at my.internal.package.common.storage.client.StorageClient.StoreFileMinIO(StorageClient.java:57)
```

The relevant line of code triggering the exception:
```
MinioClient minioClient = MinioClient.builder()
            .endpoint(storageConfiguration.getServer())
            .credentials(storageConfiguration.getAccessKey(), storageConfiguration.getSecretKey())
            .build();
```

I have tried with multiple 8.5 versions of MinIO with no luck. I have tried with and without exclusions. What am I missing here?

**Comment by timdufrane** [comment]
Sorry, not quite sure I'm understanding.

From my dependency tree: `com.squareup.okhttp3:okhttp:jar:4.12.0:compile`
From your dependency tree: `com.squareup.okhttp3:okhttp:4.12.0`

Am I missing something regarding the version here? I'm not hugely experienced in Maven so I'm trying to understand where this could be pointing to the wrong version.

**Comment by timdufrane** [comment]
Just an update on this, looks like my Kotlin transitive dependencies were getting wonky in my importing project, had to add exclusions for those dependencies and add manual dependency entries.

```
        <dependency>
            <groupId>my.internal</groupId>
            <artifactId>storage</artifactId>
            <version>3-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib-jdk8</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.8.21</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.8.21</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
            <scope>compile</scope>
        </dependency>
```

(for anyone who may be experiencing the same issues as I did, as I didn't find much help in sorting this out elsewhere)
