### ISSUE TITLE
Listbuckets signature mismatch with localhost:9000

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#205]
Checking what could be the issue.. 

~~~
scala> client.listBuckets()
Please open an issue with this bug at http://github.com/minio/minio-java
<?xml version="1.0"?><Error xmlns=""><Code>SignatureDoesNotMatch</Code><HostId>3L137</HostId><Message>The request signature we calculated does not match the signature you provided.</Message><RequestId>3L137</RequestId><Resource>/</Resource></Error>
io.minio.client.errors.InternalClientException
	at io.minio.client.Client.parseError(Client.java:284)
	at io.minio.client.Client.listBuckets(Client.java:650)
	at .<init>(<console>:10)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)


scala> 
~~~

**Comment by harshavardhana** [comment]
Ah the headers should be ignored.. 

~~~
GET
/

accept-encoding:gzip
date:Sun, 12 Jul 2015 23:40:08 UTC
host:localhost:9000
user-agent:minio-java/0.1.0 (Linux; amd64)
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150712T234008Z 

accept-encoding;date;host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
AWS4-HMAC-SHA256
20150712T234008Z
20150712/milkyway/s3/aws4_request
~~~

We have to perhaps filter these out before we send them in.

**Comment by harshavardhana** [comment]
> accept-encoding;date;host;user-agent;x-amz-content-sha256;x-amz-date

Interesting part here is that even after skipping user-agent through ignoredheader it is still being sent through the signature stream, we need to see why and also some odd accept-encoding header is also sent. Perhaps this is due to some Google's own header addition through their http client package. 

Also looks like 'date' and 'x-amz-date' both are being set either one would suffice as signed headers, just to avoid future problems.

**Comment by fkautz** [comment]
I don't feel comfortable unsetting either, x-amz-date is the recommended way for signing V4, but simultaneously unsetting date may have adverse issues with proxies. They are both forced to the same value, so should be ok.

**Comment by harshavardhana** [comment]
> I don't feel comfortable unsetting either, x-amz-date is the recommended way for signing V4, but simultaneously unsetting date may have adverse issues with proxies. They are both forced to the same value, so should be ok.

Setting them as part of a header is benign, but using them as part of signature signing is not - either one should be used.

Minimal headers which i see being sent by other libraries for a list_buckets() should be just the following. 

Python list_buckets.py
~~~
AWS4-HMAC-SHA256 Credential=YW9OTO0DL5O5GT6OJ3GU/20150713/milkyway/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=acfd388782076dbb0f8e26262b5ee5920e4c4c2a903050d7741d390e3f767c88
~~~

Javascript list_buckets.js
~~~
AWS4-HMAC-SHA256 Credential=YW9OTO0DL5O5GT6OJ3GU/20150713/milkyway/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=fcbb4d979433efc2d0cbb265a7e7be3087bbb671c9a9a3c920d674463e3bf816
~~~

Golang list-buckets.go
~~~
AWS4-HMAC-SHA256 Credential=YW9OTO0DL5O5GT6OJ3GU/20150713/milkyway/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a0d33bd89855265b577dad61fad5840ce8c9f395de85dec092a524a2bb94636e
~~~

**Comment by fkautz** [comment]
They don't show up on the list since it is non destructive, but probably do show up on put.

**Comment by fkautz** [comment]
Let's leave the date header set but remove it from the signed list
