### ISSUE TITLE
EOFException on listBuckets() when request sent to s3.amazonaws.com without access keys

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#206]
Listbuckets() operation should handle this with appropriate error. 

~~~
scala> client.listBuckets()
java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.google.api.client.xml.Xml.parseElementInternal(Xml.java:245)
	at com.google.api.client.xml.Xml.parseElement(Xml.java:222)
	at io.minio.client.Client.parseXml(Client.java:312)
	at io.minio.client.Client.parseError(Client.java:267)
	at io.minio.client.Client.listBuckets(Client.java:651)
	at .<init>(<console>:10)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)


scala>
~~~

**Comment by fkautz** [comment]
Can you check if this is still a problem?

**Comment by harshavardhana** [comment]
Yes its fixed. 

~~~
groovy:000> client.listBuckets()
input contained no data
        at org.xmlpull.mxp1.MXParser.fillBuf (MXParser.java:3003)
        at org.xmlpull.mxp1.MXParser.more (MXParser.java:3046)
        at org.xmlpull.mxp1.MXParser.parseProlog (MXParser.java:1410)
        at org.xmlpull.mxp1.MXParser.nextImpl (MXParser.java:1395)
        at org.xmlpull.mxp1.MXParser.next (MXParser.java:1093)
        at com.google.api.client.xml.Xml.parseElementInternal (Xml.java:245)
        at com.google.api.client.xml.Xml.parseElement (Xml.java:222)
        at io.minio.client.Client.parseXml (Client.java:313)
        at io.minio.client.Client.parseError (Client.java:268)
        at io.minio.client.Client.listBuckets (Client.java:680)
        at io.minio.client.Client$listBuckets$0.call (Unknown Source)
groovy:000> 
~~~

**Comment by fkautz** [comment]
Can you enable debugging and rerun this?

**Comment by harshavardhana** [comment]
The issue is that without access keys for  's3.amazonaws.com' listBuckets() returns '307' 

So we need to handle TemporaryRedirect 

~~~
groovy:000> client.listBuckets()
307
input contained no data
        at org.xmlpull.mxp1.MXParser.fillBuf (MXParser.java:3003)
        at org.xmlpull.mxp1.MXParser.more (MXParser.java:3046)
        at org.xmlpull.mxp1.MXParser.parseProlog (MXParser.java:1410)
        at org.xmlpull.mxp1.MXParser.nextImpl (MXParser.java:1395)
        at org.xmlpull.mxp1.MXParser.next (MXParser.java:1093)
        at com.google.api.client.xml.Xml.parseElementInternal (Xml.java:245)
        at com.google.api.client.xml.Xml.parseElement (Xml.java:222)
        at io.minio.client.Client.parseXml (Client.java:314)
        at io.minio.client.Client.parseError (Client.java:269)
        at io.minio.client.Client.listBuckets (Client.java:681)
        at io.minio.client.Client$listBuckets$0.call (Unknown Source)
groovy:000>
~~~

**Comment by fkautz** [comment]
Also, list buckets shouldn't return a 307... can you turn on debugging still?

        client.enableLogging();

**Comment by fkautz** [comment]
Handling redirect and treating redirect on listbuckets (GET on /) as Forbidden.

**Comment by harshavardhana** [comment]
with debugging 

~~~
groovy:000> client.listBuckets()
-------------- REQUEST  --------------
GET https://s3.amazonaws.com/
Accept-Encoding: gzip
User-Agent: minio-java/dev (Linux; amd64)

curl -v --compressed -H 'Accept-Encoding: gzip' -H 'User-Agent: minio-java/dev (Linux; amd64)' -- 'https://s3.amazonaws.com/'
-------------- RESPONSE --------------
HTTP/1.1 307 Temporary Redirect
Server: AmazonS3
x-amz-request-id: A28731D234D23251
Content-Length: 0
x-amz-id-2: s0Dr4ylkL3AXICL5gju5+buDsKqZbEdoW4mxy2rZ/jZm9a/jahhQAioNzgcm3ELt
Date: Mon, 13 Jul 2015 02:56:06 GMT
Location: http://aws.amazon.com/s3/

null
        at io.minio.client.Client.listBuckets (Client.java:687)
        at io.minio.client.Client$listBuckets$0.call (Unknown Source)
groovy:000>
~~~
