### ISSUE TITLE
statObject tries to read error body - throws an invalid exception

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#255]
HEAD request on an object has no body, it shouldn't try to read

~~~
./build/install/minio-java-examples/bin/stat-object
StatObject app
Exception in thread "main" java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.google.api.client.xml.Xml.parseElementInternal(Xml.java:245)
	at com.google.api.client.xml.Xml.parseElement(Xml.java:222)
	at io.minio.MinioClient.parseXml(MinioClient.java:376)
	at io.minio.MinioClient.parseError(MinioClient.java:301)
	at io.minio.MinioClient.statObject(MinioClient.java:230)
	at io.minio.examples.StatObject.main(StatObject.java:34)
~~~

**Comment by harshavardhana** [comment]
Invalid issue cannot reproduce it.. closing it for now.
