### ISSUE TITLE
java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@170573c4

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#353]
```
$ java -cp '.:minio-1.0.1-all.jar' FunctionalTest http://localhost:9000 WLGDGYAQYIGI833EV05A BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF
Test: makeBucket(String bucketName)
---------START-HTTP---------
PUT /minio-java-test-38qjbav HTTP/1.1
x-amz-acl: private
Host: localhost:9000
User-Agent: Minio (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20160206T080747Z
Authorization: AWS4-HMAC-SHA256 Credential=WLGDGYAQYIGI833EV05A/20160206/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@170573c4
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.minio.MinioClient.execute(MinioClient.java:487)
	at io.minio.MinioClient.executePut(MinioClient.java:684)
	at io.minio.MinioClient.makeBucket(MinioClient.java:1412)
	at io.minio.MinioClient.makeBucket(MinioClient.java:1331)
	at FunctionalTest.makeBucket_test1(FunctionalTest.java:91)
	at FunctionalTest.main(FunctionalTest.java:689)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	... 15 more
```

Works fine with an 'http://10.0.0.3:9000'

**Comment by iglaweb** [comment]
I have the same issue, use okhttp 2.7.5, the error appears while downloading big files over https (600 Mb).

**Comment by harshavardhana** [comment]
This bug is not reproducible anymore. Closing

**Comment by samirsamedov** [comment]
I had same erro with RETROFIT web services Our , server was DigitalOcean Db related with Mysql, how ever our version was old when we change it problem gone

**Comment by balamurugana** [comment]
@samirsamedov could you tell me what version of java and okhttp you use to get rid of this problem?

**Comment by samirsamedov** [comment]
I will write every detail dont worry, our guy got asleep right now me on Android side he is on web side

**Comment by balamurugana** [comment]
@samirsamedov No problem :+1:

**Comment by samirsamedov** [comment]
It  was about the version of our Node.js, above 6 is needed.

**Comment by balamurugana** [comment]
@samirsamedov I couldn't able to get you.  Are you using minio-java with S3 server where the server is written in node.js?

**Comment by samirsamedov** [comment]
Ohk we use WinSCP to connect our server its Linuz based Server , after login  are able to see folders etc. And with our error and updating Node.js; in server side we are able to use its terminal like CMD in windows , I asked some more details, if you type some thing like that "Node.js linuz centos7" you will find some shortcuts to use in terminal like yum url... of something or wget url... and this is how they updated Node.js  with comend. I am not so experienced in web side just wanted to write some clues to help others.
