### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by danyaljj** [minio/minio-java#409]
I keep getting `SocketTimeoutException` exceptions. 
Any ideas what potentially causes this? 
On a similar note, how can I set the timeout parameters? (if they are exposed to the java api). 

```
Exception in thread "main" java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.minio.MinioClient.execute(MinioClient.java:699)
	at io.minio.MinioClient.executePut(MinioClient.java:949)
	at io.minio.MinioClient.executePut(MinioClient.java:973)
	at io.minio.MinioClient.putObject(MinioClient.java:1934)
	at io.minio.MinioClient.putObject(MinioClient.java:1956)
	at io.minio.MinioClient.putObject(MinioClient.java:1840)
	at Datastore.publishFile(Datastore.java:113)
	at Datastore.publishFile(Datastore.java:91)
	at Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 27 more
```

**Comment by harshavardhana** [comment]
> I keep getting SocketTimeoutException exceptions. 
> Any ideas what potentially causes this? 
> On a similar note, how can I set the timeout parameters? (if they are exposed to the java api).

is the endpoint s3? what the size of the object being uploaded?

**Comment by danyaljj** [comment]
The end point is our own server. 
The file is around 2MB. I was thinking it might be because our network is slow. Still even if that's the problem, this is not an informative error reporting ...

**Comment by harshavardhana** [comment]
> The end point is our own server. 
> The file is around 2MB. I was thinking it might be because our network is slow. Still even if that's the problem, this is not an informative error reporting ...

Okay the timeout happens at network layer, to make this informative we just have to catch and provide some other exception but i don't know if that helps either way. 

The exception is generated by the HTTP library, it is not ideal to catch these exceptions.

**Comment by danyaljj** [comment]
Still, you should have a way to set some timeouts; right?

**Comment by harshavardhana** [comment]
> Still, you should have a way to set some timeouts; right?

There is no way to set it right now but okhttp library would certainly have it. We will explore and provide a way to do it.

**Comment by balamurugana** [comment]
Timeout can be done in okhttp by https://github.com/square/okhttp/wiki/Recipes#timeouts

**Comment by danyaljj** [comment]
I faced the issue again, but upgrading the minio server it got resolved.
