### ISSUE TITLE
DateTimeFormatter exception!

### ISSUE THREAD

**Issue by rafaelsisweb** [minio/minio-java#419]
Throwing exception in DateTimeFormat (line 370) when put to sa-eas-1 region.

This exception just happen during "updateRegionCache(bucketName);"

Even with this exception the file is sent well.

```
jul 14, 2016 12:41:01 PM io.minio.http.HeaderParser set
GRAVE: exception occured: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.minio.http.HeaderParser.set(HeaderParser.java:71)
	at io.minio.MinioClient.execute(MinioClient.java:714)
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:804)
	at io.minio.MinioClient.executePut(MinioClient.java:972)
	at io.minio.MinioClient.putObject(MinioClient.java:1934)
	at io.minio.MinioClient.putObject(MinioClient.java:1956)
	at io.minio.MinioClient.putObject(MinioClient.java:1840)
	at com.betha.di.services.S3Upload.alternativeUploadS3(S3Upload.java:73)
	at com.betha.di.services.S3Upload.upload(S3Upload.java:54)
	at com.betha.di.StartIntegration.getExtraction(StartIntegration.java:72)
	at com.betha.di.StartIntegration.main(StartIntegration.java:45)
Caused by: java.lang.IllegalArgumentException: Invalid format: "Thu, 14 Jul 2016 15:41:01 GMT"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
	at io.minio.ResponseHeader.setDate(ResponseHeader.java:89)
	... 15 more
```

**Comment by balamurugana** [comment]
@rafaelsisweb This issue is fixed by https://github.com/minio/minio-java/commit/ff1d0aedf5b6e3ccc10b5e4423b914a015012222 in current master.  Can you check whether its working for you?

**Comment by rafaelsisweb** [comment]
hy @balamurugana i'll check that.

PS: It's possivel to deliver a SNAPSHOT version on maven repository?

**Comment by harshavardhana** [comment]
> hy @balamurugana i'll check that.
> 
> PS: It's possible to deliver a SNAPSHOT version on maven repository?

@rafaelsisweb will be uploading a new release today.

**Comment by harshavardhana** [comment]
@rafaelsisweb - http://search.maven.org/#artifactdetails%7Cio.minio%7Cminio%7C2.0.1%7Cjar

**Comment by harshavardhana** [comment]
@rafaelsisweb closing this, please re-open if seen again.
