### ISSUE TITLE
getBucketAccessPolicy(bucketName, objectPrefix) returns null 

### ISSUE THREAD

**Issue by NitishT** [minio/minio-java#435]
Create a Bucket and an Object

```
client.putObject(BUCKET, "uploadsKey", data, 11, APPLICATION_OCTET_STREAM);
```

Then try to set policy using 
```
client.setBucketPolicy(BUCKET, "uploads", BucketPolicy.WriteOnly);
```
The line
```
policy = getBucketAccessPolicy(bucketName, objectPrefix);
```
in setBucketPolicy() sets the policy to null.

**Comment by harshavardhana** [comment]
Following example seems to be working fine 

```
import java.lang.StringBuilder;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.InvalidKeyException;

import org.xmlpull.v1.XmlPullParserException;

import io.minio.MinioClient;
import io.minio.BucketPolicy;
import io.minio.errors.MinioException;

public class SetBucketPolicy {
  public static void main(String[] args)
    throws IOException, NoSuchAlgorithmException, InvalidKeyException, XmlPullParserException {
    // Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY and my-bucketname are
    // dummy values, please replace them with original values.
    // For Amazon S3 endpoint, region is calculated automatically
    try {
      MinioClient minioClient = new MinioClient("https://play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");

      // Create some content for the object.
      StringBuilder builder = new StringBuilder();
      for (int i = 0; i < 1000; i++) {
        builder.append("Sphinx of black quartz, judge my vow: Used by Adobe InDesign to display font samples. ");
        builder.append("(29 letters)\n");
        builder.append("Jackdaws love my big sphinx of quartz: Similarly, used by Windows XP for some fonts. ");
        builder.append("(31 letters)\n");
        builder.append("Pack my box with five dozen liquor jugs: According to Wikipedia, this one is used on ");
        builder.append("NASAs Space Shuttle. (32 letters)\n");
        builder.append("The quick onyx goblin jumps over the lazy dwarf: Flavor text from an Unhinged Magic Card. ");
        builder.append("(39 letters)\n");
        builder.append("How razorback-jumping frogs can level six piqued gymnasts!: Not going to win any brevity ");
        builder.append("awards at 49 letters long, but old-time Mac users may recognize it.\n");
        builder.append("Cozy lummox gives smart squid who asks for job pen: A 41-letter tester sentence for Mac ");
        builder.append("computers after System 7.\n");
        builder.append("A few others we like: Amazingly few discotheques provide jukeboxes; Now fax quiz Jack! my ");
        builder.append("brave ghost pled; Watch Jeopardy!, Alex Trebeks fun TV quiz game.\n");
        builder.append("---\n");
      }

      // Create a InputStream for object upload.
      ByteArrayInputStream bais = new ByteArrayInputStream(builder.toString().getBytes("UTF-8"));

      minioClient.putObject("unknownbucket", "downloadsKey", bais, bais.available(), "application/octet-stream");
      minioClient.setBucketPolicy("unknownbucket", "downloads", BucketPolicy.WriteOnly);
    } catch (MinioException e) {
      System.out.println("Error occured: " + e);
    }
  }
}
```

**Comment by NitishT** [comment]
I was trying to do this via a test case

```
  @Test
  public void testSetBucketPolicy()
    throws InvalidBucketNameException, InvalidObjectPrefixException, NoSuchAlgorithmException, 
    InsufficientDataException, IOException, InvalidKeyException, NoResponseException, 
    XmlPullParserException, ErrorResponseException, InternalException, 
    NoSuchBucketPolicyException, MinioException {

	    MockWebServer server = new MockWebServer();
	    MockResponse response1 = new MockResponse();

	    response1.addHeader("Date", SUN_29_JUN_2015_22_01_10_GMT);
	    response1.setResponseCode(200);

	    server.enqueue(response1);
	    server.start();

	    MinioClient client = new MinioClient(server.url(""));
	    
	    String inputString = HELLO_WORLD;
	    ByteArrayInputStream data = new ByteArrayInputStream(inputString.getBytes(StandardCharsets.UTF_8));

	    client.putObject(BUCKET, "uploadsKey", data, 11, APPLICATION_OCTET_STREAM);
	    client.setBucketPolicy(BUCKET, "uploads", BucketPolicy.WriteOnly);
	    
	    
  }
```

**Comment by NitishT** [comment]
Is there something I am missing here?

**Comment by harshavardhana** [comment]
> Is there something I am missing here?

Something to do with MockServer.

**Comment by NitishT** [comment]
I took the changes from @nl5887 and executed the same test. Now there is a timeout. 

Any suggestions on how to go about writing the test case? 

```
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.minio.MinioClient.execute(MinioClient.java:807)
	at io.minio.MinioClient.executeGet(MinioClient.java:982)
	at io.minio.MinioClient.getBucketAccessPolicy(MinioClient.java:2221)
	at io.minio.MinioClient.setBucketPolicy(MinioClient.java:2173)
	at io.minio.MinioClientTest.testSetBucketPolicy(MinioClientTest.java:669)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 41 more
```

**Comment by nl5887** [comment]
In your example you're enqueuing one response, with two requests. The second request is waiting for a response, but that one is not enqueued.

Enqueue responses equally with the number of requests. Also it will be great to mock the exact responses from minio / s3, setting body, content-type and status code. You can see what is being returned by using `mc -debug ...commands...` .

Enqueing extra responses:
```
server.enqueue(new MockResponse().setBody("hello, world!"));
```

**Comment by NitishT** [comment]
Thanks @nl5887 I will try this. 

Will keep you posted.

**Comment by NitishT** [comment]
Closing this as the null response has been handled and the issue was with the test case.

**Comment by harshavardhana** [comment]
> Closing this as the null response has been handled and the issue was with the test case.

Thanks @NitishT

**Comment by NitishT** [comment]
This is the updated test case after comments from @nl5887 
```
 @Test
  public void testSetBucketPolicy()
    throws InvalidBucketNameException, InvalidObjectPrefixException, NoSuchAlgorithmException, 
    InsufficientDataException, IOException, InvalidKeyException, NoResponseException, 
    XmlPullParserException, ErrorResponseException, InternalException, 
    NoSuchBucketPolicyException, MinioException {

	    MockWebServer server = new MockWebServer();
	    MockResponse response1 = new MockResponse();
	    MockResponse response2 = new MockResponse();
	    MockResponse response3 = new MockResponse();

	    response1.addHeader("Date", SUN_29_JUN_2015_22_01_10_GMT);
	    response1.setResponseCode(200);

	    response2.addHeader("Date", SUN_29_JUN_2015_22_01_10_GMT);
	    response2.setResponseCode(200);
	    BucketAccessPolicy none = BucketAccessPolicy.none();
	    response2.setBody(gson.toJson(none));

	    response3.addHeader("Date", SUN_29_JUN_2015_22_01_10_GMT);
	    response3.setResponseCode(200);
	    
	    server.enqueue(response1);
	    server.enqueue(response2);
	    server.enqueue(response3);
	    server.start();

	    MinioClient client = new MinioClient(server.url(""));
	    
	    String inputString = HELLO_WORLD;
	    ByteArrayInputStream data = new ByteArrayInputStream(inputString.getBytes(StandardCharsets.UTF_8));

	    client.putObject(BUCKET, "uploadsKey", data, 11, APPLICATION_OCTET_STREAM);
	    client.setBucketPolicy(BUCKET, "uploads", BucketPolicy.WriteOnly);
	    
  }
```

This is passing locally. Could @nl5887 or @harshavardhana please take a look if this is the correct way to do this. I will then create a pull request.

**Comment by harshavardhana** [comment]
> This is passing locally. Could @nl5887 or @harshavardhana please take a look if this is the correct way to do this. I will then create a pull request.

This looks good @NitishT - would need some comments other than that :+1: . // cc @nl5887 ?

**Comment by NitishT** [comment]
Great! I will add comments and add few other tests for boundary cases.
