### ISSUE TITLE
NullPointerException when using copyObject method

### ISSUE THREAD

**Issue by emrekanca** [minio/minio-java#559]
I can use all other methods of java sdk but copyObject won't work

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: java.lang.NullPointerException: null
	at io.minio.Signer.setSigningKey(Signer.java:199)
	at io.minio.Signer.signV4(Signer.java:231)
	at io.minio.MinioClient.execute(MinioClient.java:811)
	at io.minio.MinioClient.executePut(MinioClient.java:1083)
	at io.minio.MinioClient.copyObject(MinioClient.java:1578)
	at io.minio.MinioClient.copyObject(MinioClient.java:1470)
	at appkap.estate.daos.MinioDAO$$anonfun$draftToNormal$1.apply(MinioDAO.scala:86)
	at appkap.estate.daos.MinioDAO$$anonfun$draftToNormal$1.apply(MinioDAO.scala:79)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at appkap.estate.daos.MinioDAO.draftToNormal(MinioDAO.scala:79)

Signer.java L199 =>
    byte[] dateRegionKey = sumHmac(dateKey, this.region.getBytes(StandardCharsets.UTF_8));

**Comment by balamurugana** [comment]
@emrekanca It looks like a bug in `v3.0.3`. Can you confirm whether `v3.0.4` works for you?

**Comment by emrekanca** [comment]
Yes it works

**Comment by balamurugana** [comment]
Already fixed.
