### ISSUE TITLE
Tests fail with master Minio but not with play.minio.io

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-java#579]
./gradlew runFunctionalTest gives the following error:

```
Test: removeObject(final String bucketName, final Iterable<String> objectNames)                                                                                  [11/644]
error occured
ErrorResponse(code=MissingContentMD5, message=Missing required header for this request: Content-Md5., bucketName=null, objectName=null, resource=/minio-java-test-1mdiula
, requestId=3L137, hostId=3L137)
request={method=POST, url=http://localhost:9001/minio-java-test-1mdiula?delete=, headers=Host: localhost:9001
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: b542974fce9a1bea0370119bc29d681fbf85d9e9fddadb0bbad1cea20a1035e9
x-amz-date: 20170521T183721Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170521/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-05-03T09-04-56Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14C0B2F4F7E0175D
Date: Sun, 21 May 2017 18:37:21 GMT
Transfer-Encoding: chunked
}

        at io.minio.MinioClient.execute(MinioClient.java:1104)
        at io.minio.MinioClient.executePost(MinioClient.java:1251)
        at io.minio.MinioClient.removeObject(MinioClient.java:2176)
        at io.minio.MinioClient.access$000(MinioClient.java:158)
        at io.minio.MinioClient$4$1.populate(MinioClient.java:2254)
        at io.minio.MinioClient$4$1.hasNext(MinioClient.java:2275)
        at FunctionalTest.removeObject_test2(FunctionalTest.java:724)
        at FunctionalTest.runTests(FunctionalTest.java:1549)
        at FunctionalTest.main(FunctionalTest.java:1630)
:functional:runFunctionalTest FAILED
```

**Comment by balamurugana** [comment]
The current head of minio server has a bug.

**Comment by harshavardhana** [comment]
Look at the latest comment @balamurugana , we should keep this issue open until we decide on the SPEC related issue.

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio/issues/4383 why this issue happens.
