### ISSUE TITLE
mint fails for s3 gateway on putobject test

### ISSUE THREAD

**Issue by poornas** [minio/minio-java#615]
putObject fails when run against s3 gateway. Needs to be investigated. This was run against build version of minio as of Sep 25.
```
Test: makeBucket(String bucketName)
Test: listBuckets()
Test: bucketExists(String bucketName)
Test: removeBucket(String bucketName)
Test: putObject(String bucketName, String objectName, String filename)
```

```error occured
ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/minio-java-test-2jssbvd/minio-java-test-7sv5ke, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://192.168.1.157:9002/minio-java-test-2jssbvd/minio-java-test-7sv5ke, headers=Content-Type: application/octet-stream
Host: 192.168.1.157:9002
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 39484377f66fa326bc696c955a509b3a38ed7e522084a5ae227e014292d09c62
x-amz-date: 20170925T235812Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170925/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=500, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-09-25T21-57-17Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14E7C02B8B3EF32D
Date: Mon, 25 Sep 2017 23:58:13 GMT
Transfer-Encoding: chunked
}

	at io.minio.MinioClient.execute(MinioClient.java:1099)
	at io.minio.MinioClient.executePut(MinioClient.java:1266)
	at io.minio.MinioClient.executePut(MinioClient.java:1288)
	at io.minio.MinioClient.putObject(MinioClient.java:3480)
	at io.minio.MinioClient.putObject(MinioClient.java:3520)
	at io.minio.MinioClient.putObject(MinioClient.java:3001)
	at io.minio.MinioClient.putObject(MinioClient.java:3038)
	at FunctionalTest.putObject_test1(FunctionalTest.java:226)
	at FunctionalTest.runTests(FunctionalTest.java:1599)
	at FunctionalTest.main(FunctionalTest.java:1717)
```

Mint image built from  commit 158108152fc86c52d5543995e0e7634bf1b6da74
Minio version:
Version: 2017-09-25T21:57:17Z
Release-Tag: RELEASE.2017-09-25T21-57-17Z
Commit-ID: d3eb5815d9951fdb82d0134b7651368bab71d72e

**Comment by nitisht** [comment]
This looks like a regression after commit `2083ce8d9d97141d0d2db86f784c0074da148045`
Sent a PR https://github.com/minio/minio/pull/4972
