### ISSUE TITLE
 java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets in MinioClient.java

### ISSUE THREAD

**Issue by perisher** [minio/minio-java#634]
I ran into a crash running the latest 3.0.8: release below,
```
 java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
at io.minio.Digest.sha256Hash(Digest.java:46)
at io.minio.Signer.setCanonicalRequest(Signer.java:183)
at io.minio.Signer.signV4(Signer.java:231)
at io.minio.MinioClient.execute(MinioClient.java:981)
at io.minio.MinioClient.updateRegionCache(MinioClient.java:1114)
at io.minio.MinioClient.getRegion(MinioClient.java:1160)
at io.minio.MinioClient.executeHead(MinioClient.java:1207)
at io.minio.MinioClient.bucketExists(MinioClient.java:2842)
```
I was running on a API 17 device and it looks like StandardCharsets was added in API 19 https://developer.android.com/reference/java/nio/charset/StandardCharsets.html.

**Comment by balamurugana** [comment]
@perisher Do you still need to support Android Jelly Bean (Version 4.1 to 4.3)?

**Comment by perisher** [comment]
Yes, i do. The fix is simple, but i dont know what that implies in your code.

**Comment by balamurugana** [comment]
According to Google, Jelly Bean is unsupported Android (WRT Security patches).  Not sure whether we could support it.  Requires an internal discussion.

**Comment by harshavardhana** [comment]
AFAICS we don't need to support Jelly Bean if Google is not supporting anymore. Moving to API 19 is a valid choice here but we can discuss.
