### ISSUE TITLE
gateway-gcs: minio-java fails at teardown() stage.

### ISSUE THREAD

**Issue by ebozduman** [minio/minio-java#647]
Gateway gcs minio-java functional test fails at its last step, `teardown()`, and the error condition is not captured in the logs. That is, logs show all successful tests and the error message goes to console.
```
$ docker run -e MINT_MODE=full -e SERVER_ENDPOINT=192.168.1.22:9000 -e ACCESS_KEY=<access_key> -e SECRET_KEY=<secret_key> -e ENABLE_HTTPS=0 minio/mint:edge minio-java
Running with
SERVER_ENDPOINT: 192.168.1.22:9000
ACCESS_KEY:      <access_key>
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       full

To get logs, run 'sudo docker cp f736a040bf38:/mint/log /tmp/mint-logs'
(1/1) Running minio-java tests ... FAILED in 19 minutes and 43 seconds
error occured
ErrorResponse(code=BucketNotEmpty, message=The bucket you tried to delete is not empty, bucketName=null, objectName=null, resource=/minio-java-test-3002piv, requestId=3L137, hostId=3L137)
request={method=DELETE, url=http://192.168.1.22:9000/minio-java-test-3002piv, headers=Host: 192.168.1.22:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20171122T002933Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171122/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F940F5AA420F6A
Date: Wed, 22 Nov 2017 00:29:33 GMT
Transfer-Encoding: chunked
}

	at io.minio.MinioClient.execute(MinioClient.java:1201)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1327)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3080)
	at FunctionalTest.teardown(FunctionalTest.java:401)
	at FunctionalTest.runTests(FunctionalTest.java:2614)
	at FunctionalTest.main(FunctionalTest.java:2689)

Executed 0 out of 1 tests successfully.
```
It looks like there are still objects in the target bucket, when the teardown(), which calls removeBucket in turn, is called. Teardown() needs to clean-up/remove any existing objects in a bucket before attempting to remove the bucket.

**Comment by balamurugana** [comment]
Question is why bucket is not empty

**Comment by harshavardhana** [comment]
This is perhaps related to the bug fix https://github.com/minio/minio/commit/bbd05a8f1c995dd7b4ea8fca10e420bb9d174e6f - perhaps we should run it once and test this again?

**Comment by nitisht** [comment]
Tested with changes from PR https://github.com/minio/minio/pull/5217 all tests pass against GCS Gateway in full mode. This issue can be closed as fixed by https://github.com/minio/minio/pull/5217

```
Running with
SERVER_ENDPOINT: 127.0.0.1:9000
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       full

To get logs, run 'sudo docker cp 5421cabef74d:/mint/log /tmp/mint-logs'
(1/1) Running minio-java tests ... done in 34 minutes and 35 seconds

All tests ran successfully
```
