### ISSUE TITLE
invalid XML: no alias declared for namesapce <> when running GetBucketNotification and SetBucketNotification

### ISSUE THREAD

**Issue by roshu420** [minio/minio-java#710]
I'm trying to run GetBucketNotification from minio java examples in Github and when I run the app, it gives me `invalid XML: no alias declared for namesapce <>`. The exception is thrown when the program tries to execute `NotificationConfiguration notificationConfiguration = minioClient.getBucketNotification("bucket-name");` This is the full stack trace.
```
Exception in thread "main" java.lang.IllegalArgumentException: invalid XML: no alias declared for namesapce <>; work-around by setting XML namepace directly by calling the set method of com.google.api.client.xml.XmlNamespaceDictionary
at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:69)
at com.google.api.client.xml.XmlNamespaceDictionary.getNamespaceAliasForUriErrorOnUnknown(XmlNamespaceDictionary.java:312)
at com.google.api.client.xml.Xml.parseElementInternal(Xml.java:253)
at com.google.api.client.xml.Xml.parseElement(Xml.java:222)
at io.minio.messages.XmlEntity.parseXml(XmlEntity.java:65)
at io.minio.MinioClient.getBucketNotification(MinioClient.java:3656)
at GetBucketNotification.main(GetBucketNotification.java:26)

Process finished with exit code 1
```
The same happens when I try to run SetBucketNotification.java and I'd really appreciate any kind of help with this.

**Comment by kannappanr** [comment]
@roshu420 We do not support notifications in Gateway mode. I believe you are running against a minio instance running in Gateway mode, based on the slack conversations that I noticed. closing this issue based on that. Please feel free to re-open the issue if that is not the case.

**Comment by nitisht** [comment]
@kannappanr this is not in Gateway mode, but Server single node mode.

**Comment by gbKidCoding** [comment]
same problems `+1`

**Comment by nitisht** [comment]
We're already looking into this, will try to fix soon

**Comment by kannappanr** [comment]
Marking this issue as closed as https://github.com/minio/minio/pull/6789 has been merged. There is also another PR https://github.com/minio/minio-java/pull/725 to fix `SetBucketNotification.java` to work with Minio.
