### ISSUE TITLE
Upload with String() method does not work

### ISSUE THREAD

**Issue by eco-minio** [minio/minio-java#721]
Code exception:
```
org.apache.http.NoHttpResponseException: The target server failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[security-sdk-java-0.1.3.jar!/:na]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[security-sdk-java-0.1.3.jar!/:na]
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[security-sdk-java-0.1.3.jar!/:na]
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[security-sdk-java-0.1.3.jar!/:na]
```
Gateway error:
```
2018-10-23 21:50:46.771934 I | Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nCache-Control: no-cache, no-store, must-revalidate, private, max-age=0\r\nPragma: no-cache\r\nExpires: 0\r\nContent-Type: text/plain; charset=utf-8\r\nDate: Tue, 23 Oct 2018 21:50:46 GMT\r\nConnection: close\r\n\r\nError 400: Bad Request\nMalformed message"; err=<nil>
```

**Comment by eco-minio** [comment]
Should have filed in sdk, closing
