### ISSUE TITLE
Unable to set bucket policy from MinioClient

### ISSUE THREAD

**Issue by nicoraynaud** [minio/minio-java#748]
Hi,

I am trying to set a Bucket Policy using the MinioClient of the Java lib. 

I tried using the sample code in the javadoc without success, and I always get the same error : 

```
error occurred
ErrorResponse(code=MissingContentLength, message=You must provide the Content-Length HTTP header.
, bucketName=null, objectName=null, resource=/test-lib-opt-minio, requestId=157BB12B514ADB7A, hostId=3L137)
request={method=PUT, url=https://minio-int.intranet.opt/test-lib-opt-minio?policy=, headers=Content-Type: application/json
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
Host: minio-int.intranet.opt
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20190120T230750Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190120/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=411, headers=Server: nginx
Date: Sun, 20 Jan 2019 23:08:16 GMT
Content-Type: application/xml
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Vary: Origin
X-Amz-Request-Id: 157BB12B514ADB7A
X-Minio-Deployment-Id: ed08ea6f-ab62-4542-9067-5cabe13b6bcd
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
}

	at io.minio.MinioClient.executeReq(MinioClient.java:1192)
	at io.minio.MinioClient.execute(MinioClient.java:1050)
	at io.minio.MinioClient.executePut(MinioClient.java:1391)
	at io.minio.MinioClient.executePut(MinioClient.java:1413)
	at io.minio.MinioClient.setBucketPolicy(MinioClient.java:3938)
```

And indeed, the lib sets the content length variable of the `executePut()` private methode to 0.

I think that it needs to be set to the actual value in order to work.

Here follows the conf of the minio server just in case:
```
VERSION
2018-12-06T01:27:43Z
MEMORY
Used: 4.0 MB | Allocated: 43 GB | Used-Heap: 4.0 MB | Allocated-Heap: 11 MB
PLATFORM
Host: ******* | OS: linux | Arch: amd64
RUNTIME
Version: go1.10.2 | CPUs: 1
```

**Comment by harshavardhana** [comment]
Have you tried removing the nginx proxy and awrting directly on server ?

**Comment by deekoder** [comment]
@nicoraynaud - It seems to work. I am closing this as working as intended. Please reopen if you think it's not working.

**Comment by nicoraynaud** [comment]
Sorry, i havent had the time to double check. I trust it's working without the nginx proxy then.

But do you think it is ok to arbitrary set the content length of the queries to 0 ?
