### ISSUE TITLE
statObject NPE when object name is empty

### ISSUE THREAD

**Issue by germhaine** [minio/minio-java#819]
Calling statObject("whatever", "") provokes a NullPointerException within ResponseHeader.lastModified() because 'lastModified' field is null in this case.

using java minio-6.0.7

java.lang.NullPointerException
    at io.minio.ResponseHeader.lastModified(ResponseHeader.java:132)                                           
    at io.minio.ObjectStat.<init>(ObjectStat.java:51)
    at io.minio.MinioClient.statObject(MinioClient.java:1482)

It should at least fail the same way as putObject("whatever", "", (...)) does instead of throwing a runtime exception.

**Comment by germhaine** [comment]
Same error with java minio-6.0.11 .

**Comment by kannappanr** [comment]
@germhaine Thanks for reporting this issue. We will take a look and send a fix
