### ISSUE TITLE
Unhandled Error 503

### ISSUE THREAD

**Issue by vibbix** [minio/minio-java#842]
Just got this exception during a routine unit test:
```Caused by: io.minio.errors.InternalException: unhandled HTTP code 503.  Please report this issue at https://github.com/minio/minio-java/issues
	at io.minio.MinioClient.executeReq(MinioClient.java:1195)
	at io.minio.MinioClient.execute(MinioClient.java:1072)
	at io.minio.MinioClient.executeHead(MinioClient.java:1361)
	at io.minio.MinioClient.statObject(MinioClient.java:1558)
	at com.{SCRUBBED}.getObject(MinioObjectStoreImpl.java:139)
	... 20 more```

**Comment by kannappanr** [comment]
@vibbix Can you please elaborate more on the error and what version of minio-java you are using etc. If you are using minio in the backend or any other object storage.

**Comment by vibbix** [comment]
I'm forwarding this issue to Subnet.
