### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space With listObjectsV2

### ISSUE THREAD

**Issue by maxbroens** [minio/minio-java#859]
Hi all!

We use:
Java Mino Client: 6.0.11
Minio Server: 2020.01.16

In order to list documents in a folder which holds around 10K+ documents, we use the following code:
```
Iterator<Result<Item>> objectsIterator = minioClient.listObjects(BUCKET_NAME, folder, false)
       .iterator();
```
So we use a bucket, a prefix and recursive false.

Then we want to put all objectnames into a List, doing:
```
List<String> documentNames = new ArrayList<>();

      while (objectsIterator.hasNext()) {
        documentNames.add(objectsIterator.next()
            .get()
            .objectName());
      }
```

We get the following StackTrace:
``` 
r.c.s.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.OutOfMemoryError: Java heap space
at org.xmlpull.mxp1.MXParser.<init>(MXParser.java:340)
at org.xmlpull.mxp1.MXParserCachingStrings.<init>(MXParserCachingStrings.java:233)
at org.xmlpull.mxp1.MXParserFactory.newPullParser(MXParserFactory.java:36)
at com.google.api.client.xml.Xml.createParser(Xml.java:92)
at io.minio.messages.XmlEntity.<init>(XmlEntity.java:46)
at io.minio.messages.Owner.<init>(Owner.java:36)
at jdk.internal.reflect.GeneratedConstructorAccessor57.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.base/java.lang.Class.newInstance(Unknown Source)
at com.google.api.client.util.Types.newInstance(Types.java:116)
at com.google.api.client.util.Data.newMapInstance(Data.java:522)
at com.google.api.client.xml.Xml.parseElementInternal(Xml.java:361)
at com.google.api.client.xml.Xml.parseElementInternal(Xml.java:441)
at com.google.api.client.xml.Xml.parseElement(Xml.java:220)
at io.minio.messages.XmlEntity.parseXml(XmlEntity.java:65)
at io.minio.MinioClient.listObjectsV2(MinioClient.java:3123)
at io.minio.MinioClient.access$100(MinioClient.java:157)
at io.minio.MinioClient$4$1.populate(MinioClient.java:2990)
at io.minio.MinioClient$4$1.hasNext(MinioClient.java:3013)
```

**Comment by kannappanr** [comment]
@maxbroens You probably have to allocate more heap space Maybe this might be helpful

https://javarevisited.blogspot.com/2011/09/javalangoutofmemoryerror-permgen-space.html

**Comment by maxbroens** [comment]
We currently use 1024mb, shouldn’t that be enough? If not, what number would you recommend?

**Comment by harshavardhana** [comment]
the XML parser has changed PTAL at the latest release and let us know @maxbroens

**Comment by balamurugana** [comment]
Now low level APIs are also exposed. They can be used to do fine control. For more information http://minio.github.io/minio-java/io/minio/MinioClient.html
