### ISSUE TITLE
Exception: org. Xmlpull. V1. XmlPullParserException

### ISSUE THREAD

**Issue by hans-tan** [minio/minio-java#868]
The client encountered this problem while uploading files to the minio service.
The SDK USES 3.0.10

`org.xmlpull.v1.XmlPullParserException: end tag name </head> must be the same as start tag <link> from line 1 (position: END_TAG seen ...<script>window.routerBase = "/";</script></head>... @40:64)
	at org.xmlpull.mxp1.MXParser.parseEndTag(MXParser.java:1699)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1172)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:1230)
	at io.minio.MinioClient.getRegion(MinioClient.java:1262)
	at io.minio.MinioClient.executeHead(MinioClient.java:1309)
	at io.minio.MinioClient.bucketExists(MinioClient.java:2979)`

Could you help me with this question? Thank you

**Comment by vadmeste** [comment]
@hans-tan the client is clearly receiving a HTML response instead of XML. I guess you just have a configuration issue on your side

**Comment by kannappanr** [comment]
@hans-tan Closing this issue based on the above comment. Please feel free to reach to us at https://slack.min.io for further questions.
