### ISSUE TITLE
Unable to parse time in Object Retention 

### ISSUE THREAD

**Issue by sinhaashish** [minio/minio-java#906]
Difference in date format in S3 and MinIO.
When i try the below code
```
Retention retention = minioClient.getObjectRetention(bucketName, objectName, <<version>>);
```

**Against S3**
It works correctly giving result as 
Mode: COMPLIANCE
Retainuntil Date: `2020-04-16T10:29:50.014Z`

While with the same code it fails against MinIO

Unable to parse the date .
 It seems that the MinIo server is not storing data in correct format as S3.

Found a similar issue https://github.com/minio/minio/issues/9182

## Expected Behavior
Java Client should be able to parse the date returned by MinIo server in the same way as it does for S3

## Current Behavior

Error while parsing the date 
```
Error occurred: java.time.format.DateTimeParseException: Text '2020-04-16T10:23:52Z' could not be parsed at index 19
```

## Steps to Reproduce (for bugs)

1. **Run the code against S3 and MinIO**
```
public class SetGetObjectLockRetentionConfig {
  
  public static void main(String[] args)
    throws IOException, NoSuchAlgorithmException, InvalidKeyException, XmlPullParserException,
    InvalidResponseException, InsufficientDataException, InternalException,
    ErrorResponseException, InvalidBucketNameException, InvalidPortException,
    InvalidEndpointException, RegionConflictException, IllegalArgumentException {
    try {

      /* play.min.io for test and development. */
      MinioClient minioClient =   new MinioClient( "EndPoint",  "Access-key", "Secret-key");
      String bucketName = "testRetention";
     String objectName = "testRetentionObject";

      minioClient.traceOn(System.out);
      // Create bucket if it doesn't exist.
      boolean found = minioClient.bucketExists(bucketName);
      if (found) {
        System.out.println(bucketName+ "already exists");
      } else {
        // Create bucket  with object lock functionality enabled
        minioClient.makeBucket(bucketName, null, true);
        System.out.println(bucketName + " is created successfully with object lock functionality enabled.");
      }

      StringBuilder builder = new StringBuilder();
      for (int i = 0; i < 1; i++) {
        builder.append(
          "Sphinx of black quartz, judge my vow: Used by Adobe InDesign to display font samples. ");
        builder.append("(29 letters)\n");
        builder.append(
          "Jackdaws love my big sphinx of quartz: Similarly, used by Windows XP for some fonts. ");
        builder.append("---\n");
      }

      // Create a InputStream for object upload.
      ByteArrayInputStream bais = new ByteArrayInputStream(builder.toString().getBytes("UTF-8"));

     minioClient.putObject(bucketName, objectName, bais, new PutObjectOptions(bais.available(), -1));
      bais.close();
      System.out.println(objectName + "  is uploaded successfully");

      // Declaring config with Retention mode as Compliance and
      // retain until one year to current date.
      ZonedDateTime retentionUntil = ZonedDateTime.now().plusDays(1);
      Retention config = new Retention(RetentionMode.COMPLIANCE, retentionUntil);

 minioClient.setObjectRetention(bucketName, objectName ,<<Version_Id>>, config, true);
 Retention retention = minioClient.getObjectRetention(bucketName, objectName, <<Version_Id>>);


      System.out.println("Mode: " + retention.mode());
      System.out.println("Retainuntil Date: " + retention.retainUntilDate());
    } catch (MinioException e) {
      System.out.println("Error occurred: " + e);
    }
  }
}
```

2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by JapuDCret** [comment]
It seems that I encounter the same issue with minio connecting to Localstack while listing buckets:
```java
 io.minio.errors.XmlParserException: java.time.format.DateTimeParseException: Text '2023-01-11T07:08:34.144898Z' could not be parsed at index 19
     at io.minio.Xml.unmarshal(Xml.java:55)
     at io.minio.MinioAsyncClient.lambda$listBuckets$24(MinioAsyncClient.java:1357)
     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
     at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
     at io.minio.S3Base$1.onResponse(S3Base.java:559)
     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:829)
```

I've tested version `8.4.3` and `8.5.1`.

**Comment by balamurugana** [comment]
@JapuDCret If you are using MinIO server, this is known issue.

**Comment by JapuDCret** [comment]
> @JapuDCret If you are using MinIO server, this is known issue.

I'm using the MinIO client to create/list/upload to an S3 Bucket hosted via `localstack`.
The weird thing is, in a docker-compose setup (also using MinIO in my JavaApp and localstack for S3) it works like a charm
