### ISSUE TITLE
Webhook Notifications no sent when I put objects with Java Client

### ISSUE THREAD

**Issue by boubech** [minio/minio-java#916]
I have configured webhook on Minio RELEASE.2020-04-23T00-58-49Z

```
mc admin config get local notify_webhook
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir=
notify_webhook:app endpoint=http://app:8080/api/minio-webhook auth_token= queue_limit=0 queue_dir=

mc event list local/mybucket
arn:minio:sqs::sdd:webhook   s3:ObjectCreated:*   Filter: suffix=".xml"
```

It works with Web UI and mc client, notifications are sent.
When I put new object with java client (7.0.2), no notification are sent to webhook.

I use the same credentials and I can see events when i use the command :  mc watch
```
[2020-04-27T15:53:08Z] 5.0 KiB ObjectCreated http://localhost:9000/mybucket/my-file-from-java-client.xml
[2020-04-27T15:53:17Z] 5.0 KiB ObjectCreated http://localhost:9000/mybucket/my-file-from-web-ui.xml
[2020-04-27T15:53:57Z] 5.0 KiB ObjectCreated http://localhost:9000/mybucket/my-file-from-mc.xm
```

I try to call method getBucketNotification, a exception is thrown
```
org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name="Id", type=void.class, data=false, required=true) on field 'id' private java.lang.String io.minio.messages.NotificationCommonConfiguration.id in class io.minio.messages.QueueConfiguration at line 1
	at io.minio.Xml.unmarshal(Xml.java:55)
	at io.minio.MinioClient.getBucketNotification(MinioClient.java:4151)
```

Workaround 
I revert to version 6.0.13

**Comment by boubech** [comment]
Hello ! 

Do you know when you release the next version ?
Thank you in advance,
