### ISSUE TITLE
io.minio.errors.InternalException: unhandled HTTP code 502

### ISSUE THREAD

**Issue by SahilJain96** [minio/minio-java#958]
Getting an unhandled 502 exception while trying to hit statObject. 

[unhandled HTTP code 502.  Please report this issue at https://github.com/minio/minio-java/issues] : io.minio.errors.InternalException: unhandled HTTP code 502.  Please report this issue at https://github.com/minio/minio-java/issues [StackTrace Hash 517da95c0a54be3505b3e5d5cb37d6fada33391df471556de25ba0dc3ba0ef84]
io.minio.errors.InternalException: unhandled HTTP code 502.  Please report this issue at https://github.com/minio/minio-java/issues
        at io.minio.MinioClient.executeReq(MinioClient.java:1189)
        at io.minio.MinioClient.execute(MinioClient.java:1066)
        at io.minio.MinioClient.executeHead(MinioClient.java:1355)
        at io.minio.MinioClient.statObject(MinioClient.java:1548)
        at io.minio.MinioClient.statObject(MinioClient.java:1505)

**Comment by balamurugana** [comment]
@SahilJain96 looks like server setup issue `502 Bad Gateway`
However we will fix to throw an (new) exception `HttpException`
